### ISSUE TITLE
system ram usage

### ISSUE THREAD

**Issue by mk148a** [aeonix/aeon-legacy#100]
Hi, what is the minimum required memory for aeon daemon. I am use windows 8.1 pro.

**Comment by iamsmooth** [comment]
There is no specific minimum. It has been run on systems with 1 GB of RAM and a lot of swap, but performance is poor.

I'd recommend 8 GB or so to run comfortably. 4 GB with some swap will probably work.

**Comment by aeonix** [comment]
Answered
