### ISSUE TITLE
Transfers not transferring but reporting success

### ISSUE THREAD

**Issue by beon-tx** [aeonix/aeon-legacy#103]
I've got this issue that just started today.  Seems everytime I try to transfer coin out to Bittrex, simplewallet says the transfer was successful and gives me hashes for the transfer split but, those hashes never appear outside of simplewallet.  IE in the daemon check_tx <hash> says it can't find it on the blockchain.  I've also tried to use a pub daemon node such as node.aeon-wallet.net with simplewallet to do the transfer, trying to eliminate the daemon from the equation, with the same results.  

To recover my coin, I have been going thru and deleting my p2pstate.bin and pool_state.bin  and my related wallet files aside from keys to rebuild from the blockchain etc.  Not sure if its related to the size of the transfer or using a payment id but, I'd never ran into this issue until I started adding payment id's to the transfers as Bittrex requires them to do deposits.

In the simplewallet.log file this exception is apparently thrown but doesn't appear to stop the tx hash generation and the tx never appears in the daemon logs:

2017-Oct-07 07:19:51.919475 ERROR c:\users\arno\documents\github\aeon-0.9.12.0\src\wallet\wallet2.h:465 m_upper_transaction_size_limit <= get_object_blobsize(tx). THROW EXCEPTION: error::tx_too_big
2017-Oct-07 07:19:51.919475 c:\users\arno\documents\github\aeon-0.9.12.0\src\wallet\wallet2.h:465:struct tools::error::tx_too_big: transaction is too big, tx_size_limit = 19400, tx size = 22355, tx:

https://gist.github.com/beon-tx/e0bed4e325e4dc39e85ab08aff7a2576

**Comment by beon-tx** [comment]
btw, my name is not arno so I think either the binary builder or a dev has some paths baked in somewhere

**Comment by stoffu** [comment]
So the error message suggests that the tx size is too big. What if you try sending smaller amounts?

**Comment by beon-tx** [comment]
Yeah, Im going to try that.  I've sent larger amounts previously and never had issues so odd this would come up now.

**Comment by beon-tx** [comment]
transfers of 100 or less worked.  200 or more did not.  So somewhere inbetween is the current sweet spot.

**Comment by beon-tx** [comment]
I spoke to soon.  Have no clue wtf is going on.  I broke my transfer up into 100 coin increments and simplewallet statedthey were all successful and I had the aeond log_level set to 1.  Saw the transactions come thru and were accepted but then they are not there anymore.  Like checking w/ check_tx 
```
2017-Oct-07 09:05:50.143167 [RPC1]tx added: <e4e4a591abbb97ba723db4b00d1bf81167900f20e593215698afc1fd142eef14>

check_tx e4e4a591abbb97ba723db4b00d1bf81167900f20e593215698afc1fd142eef14
transaction wasn't found on chain: <e4e4a591abbb97ba723db4b00d1bf81167900f20e593215698afc1fd142eef14>```

**Comment by Fjodor42** [comment]
Seen this on a 1,000 AEON transfer as well - how did you say you managed to get the funds to "reappear" in simplewallet, @beon-tx?

**Comment by sammy007** [comment]
https://bitcointalk.org/index.php?topic=641696.msg22586446#msg22586446

**Comment by pslobo** [comment]
The suggestion posted by @sammy007 does indeed allow us to recover the lost funds, but it still doesn't solve the issue of how to we get Aeon out of the wallet and into an exchange that requires payment ID? Also, this does seem to be related to amount. I've tried with values far lower than this mentioned here, from 10 - 40 and nothing works.

**Comment by sammy007** [comment]
Funds are not lost until sent to wrong address.

**Comment by pslobo** [comment]
Yeah, that I know. But for the time being they are stuck in a wallet where I can't trade them... Need to cash out some aeon ;)

**Comment by aeonix** [comment]
Don't see a specific issue here
