### ISSUE TITLE
FIRST TIME USING SIMPLE WALLET HELP

### ISSUE THREAD

**Issue by damian1231** [aeonix/aeon-legacy#108]
I have made a wallet etc, but i cant connect to the daemon
i get said errors:
2017-Oct-29 00:42:14.993107 aeon v0.9.11.0()
2017-Oct-29 00:42:14.993107 Module folder: C:\Users\media\Desktop\New folder (6)\aeond.exe
2017-Oct-29 00:42:14.993107 Initializing p2p server...
2017-Oct-29 00:42:15.008707 ERROR c:\users\arno\documents\github\aeon-0.9.11.0\src\p2p\net_node.inl:113 Exception at [node_server::init_config], what=unsupported version
2017-Oct-29 00:42:15.008707 ERROR c:\users\arno\documents\github\aeon-0.9.11.0\src\p2p\net_node.inl:277 Failed to init config.
2017-Oct-29 00:42:15.008707 ERROR C:\Users\Arno\Documents\GitHub\aeon-0.9.11.0\src\daemon\daemon.cpp:174 Failed to initialize p2p server.
2017-Oct-29 00:42:15.024307 Mining has been stopped, 0 finished
2017-Oct-29 00:43:22.463056 aeon v0.9.11.0()
2017-Oct-29 00:43:22.463056 Module folder: C:\Users\media\Desktop\New folder (6)\aeond.exe
2017-Oct-29 00:43:22.463056 Initializing p2p server...
2017-Oct-29 00:43:22.463056 ERROR c:\users\arno\documents\github\aeon-0.9.11.0\src\p2p\net_node.inl:113 Exception at [node_server::init_config], what=unsupported version
2017-Oct-29 00:43:22.478656 ERROR c:\users\arno\documents\github\aeon-0.9.11.0\src\p2p\net_node.inl:277 Failed to init config.
2017-Oct-29 00:43:22.478656 ERROR C:\Users\Arno\Documents\GitHub\aeon-0.9.11.0\src\daemon\daemon.cpp:174 Failed to initialize p2p server.
2017-Oct-29 00:43:22.478656 Mining has been stopped, 0 finished

C:\Users\Arno\ --- DOES NOT EXIST, NEVER HAS, How to change path?

**Comment by stoffu** [comment]
It seems like your `aeond.exe` failed to load the file `p2pstate.bin` (which is normally located at `C:\Users\<username>\AppData\Roaming\aeon`) for some reason. Try deleting this file and running the daemon again.
