### ISSUE TITLE
[Question/Feature Request] Importing blockchain file

### ISSUE THREAD

**Issue by beenotung** [aeonix/aeon-legacy#111]
Aeon is forked from monero, I expect it has 'aeon-blockchain-import' as monero do, but about I run the `make`, I don't find the file.

I found blockchain.bin under `~/.aeon`, I guess it store the blockchain file directly without using a lmdb, so I replace it with the blockchain downloaded from mega (with deamon restart) but it doesn't work as expected, the bin file seems being ignored.

I would like to know if the import/export function is ready for aeon or I missed some flag when running the make?

**Comment by iamsmooth** [comment]
blockchain-import was added to monero after aeon was forked from it so we don't currently have that.

**Comment by aeonix** [comment]
May be supported in the rebased code.
