### ISSUE TITLE
Static file location during creation of database?

### ISSUE THREAD

**Issue by cod3gen** [aeonix/aeon-legacy#113]
Just wanted to give you the headsup when it comes to running the daemon for the first time..
In the logs, this following error is showing;
2017-Nov-18 10:41:05.720161 [P2P9]ERROR c:\users\arno\documents\github\aeon-0.9.14.0\contrib\epee\include\storages\portable_storage.h:153 portable_storage: wrong binary format, packet size = 0 less than expected sizeof(storage_block_header)=9
2017-Nov-18 10:41:05.725174 [P2P9]ERROR C:\Users\Arno\Documents\GitHub\aeon-0.9.14.0\contrib\epee\include\storages/levin_abstract_invoke2.h:196 Failed to load_from_binary in notify 2004

User Arno is not located on this computer, and neither are github map and sourcecodes, so this the application is correct that the file(s) does not exist, but it should not even be looking for them...?

**Comment by iamsmooth** [comment]
The path mentioned in the logging messages doesn't matter. It is a peculiarity of the build process that it uses displays the path where the binary was built rather that the path where the application is currently located.
