### ISSUE TITLE
aeond - how to force re-synchronization of blockchain?

### ISSUE THREAD

**Issue by fabriek-huis** [aeonix/aeon-legacy#118]
When I run `aeond` I randomly see outputs - 

```
Sync data returned unknown top block: 1000 -> 46547 [45547 blocks behind] 
SYNCHRONIZATION started
```

If I run `bc_height` from simplewallet it outputs - 
```
[wallet WmsG9M]: bc_height
1000
```

Seems to be stuck on `1000` and doesn't move? 
Have tried running the `refresh` but does nothing.. 

```
[wallet WmsG9M]: refresh
Starting refresh...
Refresh done, blocks received: 0                                
balance: 0.000000000000, unlocked balance: 0.000000000000
```
How to force re-synchronization from aeond? 

Checked the `help` but there is nothing about it in there.

**Comment by iamsmooth** [comment]
Duplicate of #117

**Comment by fabriek-huis** [comment]
Anyways I have moved to using remote nodes instead so I don’t have to sync the whole Blockchain it’s faster and takes up less disk space.

**Comment by sebinator** [comment]
same issue for me ....
