### ISSUE TITLE
Failed to mining 

### ISSUE THREAD

**Issue by cilas** [aeonix/aeon-legacy#119]
Hello!
When i start mining on aeon daemond, show this error.
2017-Dec-12 22:28:11.152986 [miner 1]Found block for difficulty: 476
2017-Dec-12 22:28:11.152986 [miner 1]ERROR C:\Users\Arno\Documents\GitHub\aeon-0.9.14.0\src\cryptonote_core\checkpoints.cpp:71 CHECKPOINT FAILED FOR HEIGHT 1000. EXPECTED HASH: <bc6458452fd0575a314089bf302f6fd68ebaa2d689c42f3365293b96bbdf1f25>, FETCHED HASH: <961e137924d36ed570fe40dcc92ed75d6a2334789aa729fce006a01d06e1bff6>
2017-Dec-12 22:28:11.168611 [miner 1]ERROR C:\Users\Arno\Documents\GitHub\aeon-0.9.14.0\src\cryptonote_core\blockchain_storage.cpp:1607 CHECKPOINT VALIDATION FAILED
2017-Dec-12 22:28:11.168611 [miner 1]ERROR C:\Users\Arno\Documents\GitHub\aeon-0.9.14.0\src\cryptonote_core\cryptonote_core.cpp:423 mined block failed verification

**Comment by qskousen** [comment]
> Found block for difficulty: 476

That is a very low difficulty. Was the blockchain fully synced? You need to be fully synced in order to start mining in aeond.

**Comment by aeonix** [comment]
Working as intended. It shouldn't be possible to mine new blocks that conflict with a checkpoint.
