### ISSUE TITLE
Windows to Linux wallet?

### ISSUE THREAD

**Issue by buterrip69** [aeonix/aeon-legacy#121]
Hey guys, i'm trying to use a wallet created on windows under linux,
is this normal?
Error: failed to load wallet: failed to read file "wallet.bin"
Are they not the same format for any reason?
I've manually compiled the wallet from github to use on debian, thanks.

**Comment by stoffu** [comment]
The wallet files are currently not portable across different platforms, unfortunately.

**Comment by superbob** [comment]
I've created my wallet on windows, and I'd like to open it in osx. Is there any way to export/import it?

**Comment by stoffu** [comment]
The only way is to restore the wallet on OSX using the seed. The command is `simplewallet --restore-deterministic-wallet`.

**Comment by superbob** [comment]
Sounds good, I'll try this.

**Comment by superbob** [comment]
That worked perfectly. Thanks !
