### ISSUE TITLE
Creating transaction failed

### ISSUE THREAD

**Issue by DravisSivard** [aeonix/aeon-legacy#124]
I posted a transaction to an exchange about 4 hours ago but the exchange has not seen the transaction. pulled open the wallet on a different machine and connected to a public node to try and see whats up. 
that connection says:
_---------------------------------
Starting refresh...
Refresh done, blocks received: 14
balance: 44.583000000000, unlocked balance: 44.583000000000
---------------------------------_

Ok so transaction didn't trigger for some reason, ok no problem just try again from the public node this time. 
_---------------------------------
[wallet WmszU3]: transfer 3 <dst.wallet.address> 44
Error: transaction <647ffcbc4a5ebd31cf3133eb925d29a417d5e8634e37f58819e1b6d23525
66d3> was rejected by daemon with status "Failed"
---------------------------------_

Normally I would check the daemon for details on exactly WHY it failed... but public node means no daemon console. My home daemon was reporting 
_---------------------------------
2017-Dec-20 10:13:28.015261 [P2P9]Block with id: <9135f7c24d67fc7ad618e231ce2d38
f59307b50ae2b23e3aa8640f02aebf0f45>
 can't be accepted for alternative chain, block height: 406
 blockchain height: 903690
--------------------------------_

EDIT - 
On further testing and trial and error I was able to connect to a daemon that let me create a transaction. ~~Will have to wait and see if it reaches the destination. (after 4 new blocks it has not).~~
Reopening the wallet running through the remote daemon shows the AEON available to spend.
Attempts to spend it result in a "Failed" error as before.

 Having a public daemon report more than "Failed" would be useful for diagnostics.

**Comment by qskousen** [comment]
I believe `9135f7c24d67fc7ad618e231ce2d38
f59307b50ae2b23e3aa8640f02aebf0f45` block shows up for everyone, I don't think it's related to this problem.
I have had issues like this before as well, mine came about from trying to send a transaction that required more fee than i had left over after the transaction. Looks like you're leaving .5 Aeon behind though which should be enough to cover the fee. However if you are attempting to spend money that was in a recent transaction (that is rejected by the node) it seems the node can still have that failed transaction in the mempool for a while and will reject any future transactions that try to use the same inputs as a double-spend. It sounds like you have tried refreshing the wallet from scratch; can you confirm you have tried that?

**Comment by stoffu** [comment]
If you have a decent computer with ~6 GB of RAM available, it's best to run your own node; this way you have the full access to the error log and you can know exactly what's going on.

By relying on a public node, you have to accept that your ability is severely limited by the public node. Ultimately, the public node can tell you whatever lies and can decide to not accept your request for whatever reason. That's the nature of public node.

If you can't run your own node, what you can do is, for example, to contact the public node operator and ask for the log.

**Comment by DravisSivard** [comment]
@stoffu  Yes and typically I do but checking against a public node to see if there were issues with my local blockchain was my first (and really only) idea.

It looks like it was finally accepted, best guess at this point is that because it was sourced from several days worth of mining deposits that the transaction was large and getting pushed further back in the line... <-guessing here as I have not looked at the actual process within the AEON chain.

Not sure if its a daemon software issue or an AEON protocol issue but knowing that a transaction has been picked up by other nodes ans is in line for the block may be a nice feature.
