### ISSUE TITLE
Ubuntu 16.04 build works, but produces warnings during make and tests fail

### ISSUE THREAD

**Issue by jeffwnelson** [aeonix/aeon-legacy#125]
Throughout the build process for my 16.04 build, I see the following warnings:
```
/source/src/crypto/slow-hash.c: In function 'cn_slow_hash':
/source/src/crypto/oaes_lib.c:896:13: warning: 'aes_ctx' may be used uninitialized in this function [-Wmaybe-uninitialized]
  if( (*_ctx)->key )
             ^
/source/src/crypto/slow-hash.c:386:15: note: 'aes_ctx' was declared here
     oaes_ctx *aes_ctx;
               ^
```

This doesn't prevent the build from completing; however, when running the built in tests, I get the following:
```
The following tests FAILED:
          1 - coretests (Failed)
          3 - difficulty (Failed)
         12 - unit_tests (Failed)
Errors while running CTest
Makefile:127: recipe for target 'test' failed
make[1]: Leaving directory '/source/build/release'
make[1]: *** [test] Error 8
Makefile:23: recipe for target 'test-release' failed
make: *** [test-release] Error 2
```

Any thoughts? Or are these warnings ones I can ignore and disregard the test results?

**Comment by stoffu** [comment]
The warning on `aes_ctx` seems non-critical, although certainly it'd be better to have it initialized with null.

The tests seem to be largely unmaintained, to my surprise (thanks for pointing it out). There have been quite some changes made to cryptonote_config.h in 2015, but the tests directory seems to be not catching up with it:

- https://github.com/aeonix/aeon/commits/master/src/cryptonote_config.h
- https://github.com/aeonix/aeon/commits/master/tests

Looks like more love is needed here :)

**Comment by iamsmooth** [comment]
Tests failing is considered 'normal' as many were broken in early Monero and the original AEON dev didn't do anything about fixing/maintaining them and neither have I.

I think best to focus on having working tests in the rebase tree and not worry about this one. It would be a very significant effort to get the tests fixed.
