### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by narutokhanh** [aeonix/aeon-legacy#126]
Sorry, 
I want to mine on vps (ubuntu) but i don't know code and how can i step setup??
Please help me

**Comment by stoffu** [comment]
For solo mining, you can just use `start_mining <address> <num_threads>` in `aeond`.

For pool mining, you need to look into other repositories such as:
- https://github.com/xmrig/xmrig
- https://github.com/fireice-uk/xmr-stak

**Comment by narutokhanh** [comment]
tks

2017-12-22 6:25 GMT+07:00 stoffu <notifications@github.com>:

**Comment by narutokhanh** [comment]
Sr, i have issue 
![untitled](https://user-images.githubusercontent.com/34752052/34289304-78c40ee2-e724-11e7-9180-897c8f798bde.png)

please fix it

**Comment by stoffu** [comment]
You should ask any questions about XMRig on their repository, not here.

That said, the problem doesn't seem to be about XMRig; your machine simply couldn't install software with `apt install`. Maybe the RAM is too small and you need to increase the size of the page file?

Anyway, please look for the solution elsewhere.

**Comment by Pajace** [comment]
Hi narutokhanh,

I've build a docker image for xmrig, you can use it easy without build xmrig yourself.
https://hub.docker.com/r/pajace/xmrig/

Welcome to here for mining, http://aeon-pool.sytes.net/
