### ISSUE TITLE
Problem when I try to transfer AEON from HitBTC

### ISSUE THREAD

**Issue by cvhainb** [aeonix/aeon-legacy#127]
Hi there,

Today, I have withdrawal my AEON coin from HitBTC to simplewallet. The transaction is completed however I still don't see it in my simplewallet. I don't know why and what I should do in the next. Please advise.

https://chainradar.com/aeon/transaction/273abdf4d1a0772bb42c08354973f42c5a04e671f5f0a500f03fb69109c6e231

For this transaction, when I check on deamon
273abdf4d1a0772bb42c08354973f42c5a04e671f5f0a500f03fb69109c6e231

I see this message: transaction wasn't found on chain: <273abdf4d1a0772bb42c08354973f42c5a04e671f5f0a500f03fb69109c6e231>

Actually I have not any idea about this. It is a small balance so it's not too important however I am trying to learn about it.

Best Regards,

Chu

**Comment by stoffu** [comment]
The only reason I can think of is that your daemon is not fully synced yet. Can you check your daemon's synced height by typing `diff` in aeond?

**Comment by cvhainb** [comment]
Thank you so much stoffu. I have typed it and I think it's fully synced.

![untitled](https://user-images.githubusercontent.com/105113/34298580-125ede7a-e751-11e7-864d-e82950116692.png)

**Comment by stoffu** [comment]
No your daemon isn't fully synced; you're having an issue that's becoming more common today somehow that the daemon gets stuck at height 1000. Please try the steps described here: https://github.com/aeonix/aeon/issues/117#issuecomment-353502728

**Comment by cvhainb** [comment]
I have posted it. Thank you so much stoffu.

**Comment by BigslimVdub** [comment]
Use a public node for mac. 
On terminal type in the the commands for opening simple wallet than add the public node address followed by port 11181 and hit enter. IT should prompt you to enter your wallet name and then password and it will sync. If you have never synced before it may take some time (10min maybe) but after that it should take no less than 10-20 seconds to sync. Make sure to type "exit" after it syncs so it will save.

Example terminal entry;
~ admin$ /Applications/aeon\ cli/HEAD-******/bin/simplewallet --daemon-address node.aeon-wallet.net 11181

Note that the ***** is your wallet compiled folder name, you will need to copy that address in.

**Comment by stoffu** [comment]
@BigslimVdub 
Use of public node should be considered as the last resort (i.e. for those who have absolutely no possibility/ability of running a full node on their own). If your hardware allows for it, you should definitely run your own node.

After all, the whole premise of AEON is to make running a full node as accessible as possible to ordinary people who may own only low end mobile devices. This is the reason behind the more lightweight PoW algorithm and the longer block time.

BTW, the wallet is actually "scanning" txes, not syncing. Syncing is the task of full node. The main difference is that scanning doesn't involve verification of txes.
