### ISSUE TITLE
Broken pipe issue

### ISSUE THREAD

**Issue by Pajace** [aeonix/aeon-legacy#128]
Hi there,

I always got the error message from aeond, is that OK or not OK?
How do it fix it or do something to let it work correctly?

```
2017-Dec-24 23:19:07.527329 [P2P5][sock 15] Some problems at write: Broken pipe:32
```

My environment: Ubuntu 16.04

**Comment by marmistrz** [comment]
I'm also affected.

**Comment by aeonix** [comment]
These messages indicate a broken peer connection. In a p2p network that is normal. They probably shouldn't be logged by default but this likely won't be fixed until after the rebase.
