### ISSUE TITLE
When using OS X and connecting to Public Node, User can not do any function after sync because SimpleWallet closes

### ISSUE THREAD

**Issue by BigslimVdub** [aeonix/aeon-legacy#131]
~ admin$ /Applications/aeon\ cli/HEAD-11111111/bin/simplewallet --daemon-address node1.aeon-wallet.net 11181

When connecting to public node and after it sync's, SimpleWallet closes and does not allow any other wallet function. If user re-opens wallet only immediately after user is prompted with "unable to connect to daemon" and wallet does refresh. Wallet DOES save when it exits from this auto-close. 

When using windows and connecting to public node, simplewallet does not close after sync is complete. It stays open and allows for user to send or make transactions or check network.

![screen shot SimpleWallet](https://user-images.githubusercontent.com/30030687/34363201-8e3f4322-ea3f-11e7-947b-785baed65459.png)

**Comment by stoffu** [comment]
You're missing `:` in the daemon URL argument: it should've been `--daemon-address node1.aeon-wallet.net:11181`. The wallet crashes due to this parsing error, which should be fixed. The same behavior is observed also with Monero's wallet, so I'll submit a patch.

Thanks for reporting this bug!

**Comment by BigslimVdub** [comment]
No problem. I meant to add the : but it runs and syncs just fine. I will retry with the : later and see how it runs.

**Comment by BigslimVdub** [comment]
Just retry with the : and it works great, no errors and can run commands with wallet open

**Comment by aeonix** [comment]
Appears resolved
