### ISSUE TITLE
Sync data returned unknown top block

### ISSUE THREAD

**Issue by nevata** [aeonix/aeon-legacy#132]
2017-Dec-29 11:23:19.914026 aeon v0.9.14.0()
2017-Dec-29 11:23:19.915027 Module folder: D:\AEON\aeond.exe
2017-Dec-29 11:23:19.917028 Initializing p2p server...
2017-Dec-29 11:23:19.919029 Binding on 0.0.0.0:11180
2017-Dec-29 11:23:19.921063 Net service binded on 0.0.0.0:11180
2017-Dec-29 11:23:19.923091 Attempting to add IGD port mapping.
2017-Dec-29 11:23:22.357148 IGD was found but reported as not connected.
2017-Dec-29 11:23:22.359150 P2p server initialized OK
2017-Dec-29 11:23:22.359150 Initializing cryptonote protocol...
2017-Dec-29 11:23:22.361151 Cryptonote protocol initialized OK
2017-Dec-29 11:23:22.361151 Initializing core rpc server...
2017-Dec-29 11:23:22.362151 Binding on 127.0.0.1:11181
2017-Dec-29 11:23:22.363152 Core rpc server initialized OK on port: 11181
2017-Dec-29 11:23:22.365154 Initializing core...
2017-Dec-29 11:23:22.366154 Loading blockchain...
2017-Dec-29 11:24:00.155443 CHECKPOINT PASSED FOR HEIGHT 1 <1440a20f078bf3264822234b347f8382606577d73d4e9d3cb7296d73889bc421>
2017-Dec-29 11:24:00.160449 CHECKPOINT PASSED FOR HEIGHT 100 <6dd13aaab16679f49ee6b2b75c7dc99b1fd09ab2282b18cb4b55b73110655742>
2017-Dec-29 11:24:00.199475 CHECKPOINT PASSED FOR HEIGHT 1000 <bc6458452fd0575a314089bf302f6fd68ebaa2d689c42f3365293b96bbdf1f25>
2017-Dec-29 11:24:00.392602 CHECKPOINT PASSED FOR HEIGHT 10000 <1ac1ebd25baf0d6ec593daa3389f1aa7e860ff2cc29f3cf1be586d245b379da4>
2017-Dec-29 11:24:00.502676 CHECKPOINT PASSED FOR HEIGHT 15000 <15567af42afc1ed00538f53b5e3822d421e3ed6372ca79f4ea4e3e3bab709a87>
2017-Dec-29 11:24:04.940646 CHECKPOINT PASSED FOR HEIGHT 175500 <3f7dd748b3b863b04654d87a387f2b65a365f467188971f3192eab2368e64a35>
2017-Dec-29 11:24:04.945651 Blockchain initialized. last block: 175592, d1174.h0.m18.s28 time ago, current difficulty: 3009203
2017-Dec-29 11:24:04.947650 Core initialized OK
2017-Dec-29 11:24:04.948650 Starting core rpc server...
2017-Dec-29 11:24:04.950652 Run net_service loop( 2 threads)...
2017-Dec-29 11:24:04.962636 [SRV_MAIN]Core rpc server started ok
2017-Dec-29 11:24:04.964622 [SRV_MAIN]Starting p2p net loop...
2017-Dec-29 11:24:04.965623 [SRV_MAIN]Run net_service loop( 10 threads)...
2017-Dec-29 11:24:05.966568 [P2P3]
**********************************************************************
The daemon will start synchronizing with the network. It may take up to several hours.

You can set the level of process detailization* through "set_log <level>" command*, where <level> is between 0 (no details) and 4 (very verbose).

Use "help" command to see the list of available commands.

Note: in case you need to interrupt the process, use "exit" command. Otherwise, the current progress won't be saved.
**********************************************************************
2017-Dec-29 11:24:16.862322 [P2P9][91.109.24.245:11180 OUT]Sync data returned unknown top block: 175593 -> 906716 [731123 blocks behind] 
SYNCHRONIZATION started
2017-Dec-29 11:24:32.485445 [P2P3][165.227.152.121:11180 OUT]Sync data returned unknown top block: 176593 -> 906717 [730124 blocks behind] 
SYNCHRONIZATION started
2017-Dec-29 11:24:55.625516 [P2P9][151.16.200.71:11180 OUT]Sync data returned unknown top block: 177393 -> 906717 [729324 blocks behind] 
SYNCHRONIZATION started
2017-Dec-29 11:24:57.075611 [P2P3][109.247.28.40:11180 OUT]Sync data returned unknown top block: 177793 -> 906717 [728924 blocks behind] 
SYNCHRONIZATION started
2017-Dec-29 11:25:12.187660 [P2P9][86.153.44.49:11180 OUT]Sync data returned unknown top block: 179193 -> 906717 [727524 blocks behind] 
SYNCHRONIZATION started
2017-Dec-29 11:25:18.337492 [P2P6][107.23.82.249:11180 OUT]Sync data returned unknown top block: 179393 -> 906716 [727323 blocks behind] 
SYNCHRONIZATION started
2017-Dec-29 11:25:56.526356 [P2P4][88.250.24.16:11180 OUT]Sync data returned unknown top block: 180793 -> 906717 [725924 blocks behind] 
SYNCHRONIZATION started

**Comment by qskousen** [comment]
This is completely normal and expected behavior. It means your node is behind the network and needs to sync.

**Comment by aeonix** [comment]
No issue here afaict
