### ISSUE TITLE
Aeonizer doesn't start

### ISSUE THREAD

**Issue by agurod42** [aeonix/aeon-legacy#136]
Hey guys, I received an email with some instructions on how mining aeon coins so I tried to follow them. I downloaded the Aeonizer mining software from this link https://www.sendspace.com/file/nnsz0i, but when I try to execute the application it doesn't shows up nor shows an error.

There are some special requisites or configuration steps that I should follow in order to be able to run the software?

AFAIK the antivirus is not blocking the execution of the app (I disabled it).

I'm running on this x64 Windows 10:

<img width="511" alt="screen shot 2018-01-03 at 11 17 19 am" src="https://user-images.githubusercontent.com/13837769/34523819-c9d29cca-f077-11e7-9b14-75b7fc08b92a.png">

**Comment by stoffu** [comment]
Most likely you're being scammed and the program is a malware.

A legitimate open-sourced software usually distributes precompiled binaries under the release section with some checksum. Anything uploaded on random file sharing sites should be considered as malware.
