### ISSUE TITLE
Error compiling Aeon in Ubuntu 16.04 

### ISSUE THREAD

**Issue by 420coupe** [aeonix/aeon-legacy#138]
[ 44%] Linking CXX executable connectivity_tool
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `boost::cpp_regex_traits<char>::transform[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:961: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `boost::cpp_regex_traits<char>::transform_primary[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:965: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
collect2: error: ld returned 1 exit status
src/CMakeFiles/connectivity_tool.dir/build.make:108: recipe for target 'src/connectivity_tool' failed
make[3]: *** [src/connectivity_tool] Error 1
make[3]: Leaving directory '/home/ubuntu/aeon/build/debug'
CMakeFiles/Makefile2:216: recipe for target 'src/CMakeFiles/connectivity_tool.dir/all' failed
make[2]: *** [src/CMakeFiles/connectivity_tool.dir/all] Error 2
make[2]: Leaving directory '/home/ubuntu/aeon/build/debug'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/aeon/build/debug'
Makefile:8: recipe for target 'build-debug' failed
make: *** [build-debug] Error 2

GCC Ver 6.3.0
Cmake Ver 3.5.1
libboost-all-dev (1.58.0.1ubuntu1)

Any help with this would be greatly appreciated.

**Comment by 420coupe** [comment]
Tried with libboost-all-dev ver 1.64, even though when compiling it reverts back to 1.58 because of the apt-get install libboost-dev-all. 

Kinda out of ideas, have tried launching a new fresh instance of 16.04 LTS and still running into the same issue.

**Comment by stoffu** [comment]
I don't see such an error on Ubuntu 16.04 LTS.
```
cmake version 3.5.1

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

Boost version: 1.58.0
```
Are you sure you're building the latest master?

**Comment by 420coupe** [comment]
Solved. 

These were commands to get it to work, from a fresh instance of 16.04. 

sudo apt-get update
sudo apt-get upgrade -y
sudo apt update
sudo apt upgrade -y

sudo fallocate -l 12G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab

sudo apt-get install cmake
sudo apt-get install g++
sudo apt-get install libboost-dev-all
sudo apt-get update
sudo apt-get upgrade -y
sudo apt update
sudo apt upgrade -y

sudo git clone https://github.com/aeonix/aeon aeon
cd aeon
sudo make

**Comment by aeonix** [comment]
Appears was caused by some non-standard config and resolved per last comment
