### ISSUE TITLE
Simplewallet fails to run

### ISSUE THREAD

**Issue by patrayman** [aeonix/aeon-legacy#139]
I get "unknown command: simple wallet" when trying to launch it after syncing.

I'm running OSX 10.13.2

Image below
<img width="667" alt="screen shot 2018-01-05 at 9 51 27 am" src="https://user-images.githubusercontent.com/35142448/34614066-2e4fc448-f1fe-11e7-9863-555d8af04789.png">

**Comment by stoffu** [comment]
You're on `aeond`, the Aeon full node application. You get the list of available commands by typing `help`. `simplewallet` is a separate CLI program responsible for managing your keys and funds.

**Comment by patrayman** [comment]
Got it, thanks for the help!
