### ISSUE TITLE
Block found late ? A time problem

### ISSUE THREAD

**Issue by phil2cr** [aeonix/aeon-legacy#140]
I thin mining pool should have noticed the Network finding block could be long: some time more than 15 minutes. " Block Found: 15 minutes ago"

But is  i look at the explorer blockchain ( https://en.minergate.com/blockchain/aeon/blocks ) i can see we got 15 block / 1 hour witch is ok.

So the problem is not a too long time between block, but a general delay on all the block.

The problem is probably a lack of miner (btw hashrate). I don't think of an software problem, your thought ?

**Comment by stoffu** [comment]
The block generation is a random process with the target 4 minute block time being only the expected average. 15min or much longer for finding the next block is perfectly normal albeit not too frequent.

**Comment by phil2cr** [comment]
Thank you for your answer

**Comment by phil2cr** [comment]
I am sorry to come back on this issue, but i notice something weird:

on my mining pool and on an other one i notice:
Block Found: 16 minutes ago
and just after: Block Found: 9 minutes ago

That mean for me ? that we are noticed of the discovery sometimes 8 to 9 minutes after the block was really discovered ? Other pool notice that , if it is a problem ?
because i think we allways must see less than one minute ago ?
Is it possible for a pool to delay the fact a block was discovered ?

**Comment by stoffu** [comment]
Sorry, please don't take any offense, but your post contains too many grammatical errors for me to fully understand your question. Please try to rephrase it, if possible.

> Is it possible for a pool to delay the fact a block was discovered ?

Yes, a miner can choose to keep a new block he found for a while and broadcast it later, as long as no other miners find a new block and broadcast.

**Comment by phil2cr** [comment]
Sorry for my english, you are right :)

You did answer to the second part of my question. But the first part was:
When i look at "Block Found:" i got this evolution:
13 minutes ago
14 minutes ago
15 minutes ago
16 minutes ago
and then jump to:
9 minutes ago
10 minutes ago
etc ...

it append regulary and i notice it is the same for some other pools.
it is strange that we jump from "16" to "9" and not from "16" to "1" or "2".

it is like, for i don't know the technical reason, the discovery of a Block was announced 9 minutes after ...

**Comment by phil2cr** [comment]
An other example : i was waiting for the block 911960 on minergate:
https://en.minergate.com/blockchain/aeon/block/911960

I keep refreshing the page until the block show up

The block was displayed with "15 minutes ago" for the first time
Height? | <911960>-- | -- Timestamp (UTC)? | 2018-01-12 02:51:10 (15 minutes ago)

It was the same on other aeon pools.

Is it normal ? To have a block showing up as discovered 15 minutes after it is actualy discovered ?
15 minutes is far more than a normal delay on a network.

**Comment by stoffu** [comment]
What MinerGate's explorer shows seems perfectly normal to me. The block arrival time can vary arbitrarily; it can be less than a minute or more than 20 minutes. But on average, there should be 15 blocks found every hour, and that's what I see on the explorer.

**Comment by phil2cr** [comment]
Yes you are right 15 block per hour is 1 per 4 minutes that is also ok for me.

But there is a delay between the 'discovery of a block' and the 'annoncement of the discovery' (between 1  20 minutes). That is my concern.

**Comment by phil2cr** [comment]
for exemple on one big pool of the network for block 911964

the pool display:
- the network was Block Found: 15 minutes ago (same on all other pools except the one that made the discovery)
- and the pool is Block Found: 5 minutes ago

so the pool discover the block 5 minutes ago but the network does not know.

after a periode of time the block 911964 it still:
- the network was Block Found: 19 minutes ago (same on all other pools except the one that made the discovery)
- and the pool is Block Found: 8 minutes ago

**Comment by phil2cr** [comment]
Same with block 911965.
it is like the annoncement of a block discovery of the big pool is taking with a big delay by the network ?

**Comment by phil2cr** [comment]
the delay for block 911966 seems ok now.

**Comment by phil2cr** [comment]
Since we have this discution, the problem seems to be solved.
. . .

**Comment by phil2cr** [comment]
There is a real problem with the time operation, if some other pool can look on that issue closer.

**Comment by stoffu** [comment]
Each block has a timestamp set by the miner, which can be inconsistent with others. Therefore, it's possible for a sequence of blocks to have a *decreasing* sequence of timestamps. The acceptable degree of this inconsistency is limited to something reasonable, though.

Different pool websites and block explorers can show block arrival time slightly differently (maybe a few minutes off), probably because of their system time setting.

In any case, everything seems normal to me. What's your problem?

**Comment by phil2cr** [comment]
Today most computers use NTP so they have an accurate time. And we can see the time of these servers are accurate.

Sorry, i explain the behavior before, and i don't find that behavior normal at all. Difficult to say if it's a software issue (miner, pool or daemon).

**Comment by stoffu** [comment]
What *specifically* is your problem?

**Comment by phil2cr** [comment]
Thank you for your time and your answers.

**Comment by aij** [comment]
It can't be normal for blocks to take that long to propagate throughout the network.

The average block time on Aeon is 4 minutes. Having a blockchain that's 9-16 minutes behind means you're likely working with outdated information, and can't effectively mine.

I can't look into it in detail right now. Is most of the network 9-16 minutes behind? If so that could be indicative of an attack. (Eg: A large enough miner might be able to mine all the blocks if they can prevent the network from reaching consensus on anyone else's blocks.)

**Comment by phil2cr** [comment]
Thanks @aij  for understanding the point.

**Comment by stoffu** [comment]
I doubt the block propagation takes that long. The inconsistency of block arrival times seen in explorers and some pools must be due to improper system time settings or something.

If there was a real issue with block propagation, we would see a lot of orphan blocks in many pools.

**Comment by stoffu** [comment]
Please close this thread as your "problem" is nonexistent.

**Comment by prox443** [comment]
@phil2cr Hi, have you find the solution for  (https://github.com/electroneum/electroneum/issues/60)
=> Error finding txpool tx meta: MDB_NOTFOUND ?

**Comment by qskousen** [comment]
@prox443 - not sure why you are asking about an electroneum issue - which
is a fork of monero - in the aeon repository.

**Comment by phil2cr** [comment]
@prox443 Yes, i updated the post:
Problem solved using Ubuntu 16.4.3 LTS
because of the libboost "1.58"

**Comment by prox443** [comment]
@phil2cr i have this version :'( can u send me email on ythacdo@gmail.com plz ?
