### ISSUE TITLE
Boost version 1.66, unsupported

### ISSUE THREAD

**Issue by rowanruseler** [aeonix/aeon-legacy#143]
[Boost version 1.66](http://www.boost.org/users/history/version_1_66_0.html) not supported. This causes the following issue on rolling release distributions:

`./aeond: error while loading shared libraries: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory`

1.66.0 has been released on December 18th, 2017 13:58 GMT

**Current workaround on Arch Linux:**
`pacman -U /var/cache/pacman/pkg/boost-libs-1.65.1-2-x86_64.pkg.tar.xz`

**Comment by aij** [comment]
That sounds like a packaging problem on Arch. You seem to be trying to run a dynamically linked executable without the library it's linked to. 

Have you tried compiling/linking against 1.66? If so, were there any problems?

**Comment by rowanruseler** [comment]
@aij - you're correct, thanks.

> Have you tried compiling/linking against 1.66?
No; apologies, I'll re-compile first next time 👍 

Able to compile with:
- GCC 7.2.1+20171224-2
- CMake 3.10.1-2
- Boost 1.66.0-1

All functioned after that.
