### ISSUE TITLE
AeonD hangs up until CMD window is clicked on and a keyboard button pressed

### ISSUE THREAD

**Issue by BigslimVdub** [aeonix/aeon-legacy#145]
I have an issue with AeonD hanging up during parts of loading. IT usually always hangs up at like "Loading Blockchain". Sometimes it will load fine and others it hangs at that line until I click on the window and press a keyboard button (usually the down arrow) and then it blows up all the past X minutes of loading information. Sometimes after the chain is fully sync, It hangs up after a block is added until I repeat the same process, usually pressing down arrow, and it loads the last X amount of blocks found to the CMD window. Sometimes I have left it there 20-30 minutes and it loads 10-20 blocks after it has hung up. 

Windows 10 Pro
No other applications running while aeonD running (until sync then simplewallet opened to refresh)
6gb ddr3
I did not have this issue with MoneroD on same hardware.

**Comment by stoffu** [comment]
It's a well known limitation that it takes quite some time to load the blockchain, but eventually it should complete. It sounds strange to me that the process sometimes succeeds and other times fails. Can you post a screenshot here, or even better, share a screen recording (at YouTube or streamable.com etc)?

**Comment by BigslimVdub** [comment]
IT seems almost as if aeonD data is getting stuck in the ram when loading and updating. I will attempt to get screen shot or video for you. It just hangs up until you press a keystroke then it all populates in the CMD window fine.

**Comment by BigslimVdub** [comment]
https://youtu.be/AWFZkMsrwVo

Added link to video. 

I also have a screenshot for after it was sync the cmd went all crazy overlapping the text lines.

**Comment by stoffu** [comment]
I don't see any crash or freeze or hang up in that video. What do you see after that?

> I also have a screenshot for after it was sync the cmd went all crazy overlapping the text lines.

Please share the screenshot.

**Comment by BigslimVdub** [comment]
![blockchainfreeze](https://user-images.githubusercontent.com/30030687/34901711-9d751fe6-f7d3-11e7-8c6f-3df9e76a1af7.jpeg)

Here is a picture from aeonD after it synced and I had it running for a bit (trying to make transactions) 

Notice how the text is overlapping. I ended up just manually closing the cmd window and waiting about 5 minutes then re-opening aeonD and it sync fine and had no issues. This usually happens every other time I try opening aeonD. Happens opening with shortcut or directly off exe file.

**Comment by stoffu** [comment]
This behavior is somewhat ugly but normal. You typed `help` to print out text while the daemon also tried to print text in order to show information about peers. It can't handle text printout operations for two different purposes at the same time; the text gets mixed.

> I ended up just manually closing the cmd window

Please don't do that, type `exit` instead so that it can finish gracefully.

In any case, I don't see any crash or hang up in your situation.

**Comment by BigslimVdub** [comment]
I did type in exit (might be in that picture) and waited 8 minutes and it wouldn't close or show any more text (the usual saving....node disconnected... ect..) so I thought it was totally hung up. 

As stated though, after waiting about 5 minutes and re-opening it ran just fine and sync ok. 

As for hang up, you can see in the video it does the normal :loading blockchain: and then it does nothing. I waited 15 minutes for it to load (usually takes about 5-6 minutes or so to fully sync) and it did not advance until I hit a keyboard stroke then it updated to the 15 minutes time it was "loading" even though only 2 minutes after it started loading it technically was verifying everything.

**Comment by stoffu** [comment]
Can you try to make a longer screen record, if you like? In your previous video, I don't see it hanging up or stalling.

**Comment by BigslimVdub** [comment]
I added a better video. This time I waited 25 minutes not touching it and it didn’t continue updating until I hit the spacebar. 
https://youtu.be/P775X5MbGOY

It does continue to sync fine after I hit a spacebar and it keeps loading. AeonD is running 5.9 of 6 available GB of ram and 2.3 GB of pagefile in Windows (I have it set to 16gb available pagefile). No other programs running while aeonD is operating.

**Comment by stoffu** [comment]
Thanks for the new video. Indeed, it's very strange that aeond started moving when you hit the spacebar. I also run aeond on Windows but have never observed such a behavior.

I have no clue how to fix this issue, unfortunately. Hopefully, someone familiar with Windows event handling might be able to fix it. Or the upcoming rebase will likely solve everything.

**Comment by Juzzle1** [comment]
This has nothing to do with aeond... It's happening because you're entering text selection mode. (left clicking / select). Windows freezes the output of a command prompt / console window in this mode so you have a chance to select text before it scrolls off the screen. Right clicking or pressing a keyboard button cancels text selection and output resumes.

**Comment by BigslimVdub** [comment]
added 16GB ram to this and aeonD syncs in about 3 minutes now. But I still have the hangup issue. 40 minutes I waited this time and aeonD was hung up would not close. Manually closed and re-open and it re-sync in 3 minutes and I was able to close properly no issues. 

It looks like when I use a desktop shortcut to aeonD it has this locking up issue (I use the daemon for other computers on the network unable to run aeon for hardware reasons). When I run normal aeonD from the build folder it runs fine every time. 

As you can see in the picture it locks up on the last line when "exit" is run. 
9.2GB ram, 2% cpu usage. Absolutely nothing would unfreeze aeonD other than manually closing it. 
![aeond hangup](https://user-images.githubusercontent.com/30030687/35311570-cf99e216-007c-11e8-8d28-35d317dc8563.PNG)

**Comment by BigslimVdub** [comment]
Closing issue due to legacy software version.  Newest version 0.12.0 has no issues running daemon or freezing up.
