### ISSUE TITLE
Is it normal? Simplewallet [RPC0] Block is already in blockchain

### ISSUE THREAD

**Issue by myaeon-ru** [aeonix/aeon-legacy#148]
**What and who caused this repeated messages?
Here someone find block!**

Jan 24 22:44:52 ubuntu simplewallet[1839]: 2018-Jan-24 22:43:52.074902 [RPC0]Processed block: <eb649e384eacadf9e61e738e4957fbdc773dd1d0393dfdfb749e3c3b31cbf93c>, height 916474, 48(3/45)ms

**Block was processed and then till be found next block in simple wallet log will be this repeated message:**

Jan 24 22:44:52 ubuntu simplewallet[1839]: 2018-Jan-24 22:43:52.113998 [RPC0]Block is already in blockchain: eb649e384eacadf9e61e738e4957fbdc773dd1d0393dfdfb749e3c3b31cbf93c
Jan 24 22:44:52 ubuntu simplewallet[1839]: 2018-Jan-24 22:43:52.114584 [RPC0]Refresh done, blocks received: 1, balance: 6.013000000000, unlocked: 6.013000000000
Jan 24 22:44:52 ubuntu simplewallet[1839]: 2018-Jan-24 22:44:12.154076 [RPC0]Block is already in blockchain: eb649e384eacadf9e61e738e4957fbdc773dd1d0393dfdfb749e3c3b31cbf93c
Jan 24 22:44:52 ubuntu simplewallet[1839]: 2018-Jan-24 22:44:12.154660 [RPC0]Refresh done, blocks received: 0, balance: 6.013000000000, unlocked: 6.013000000000
Jan 24 22:44:52 ubuntu simplewallet[1839]: 2018-Jan-24 22:44:32.194070 [RPC0]Block is already in blockchain: eb649e384eacadf9e61e738e4957fbdc773dd1d0393dfdfb749e3c3b31cbf93c
Jan 24 22:44:52 ubuntu simplewallet[1839]: 2018-Jan-24 22:44:32.194658 [RPC0]Refresh done, blocks received: 0, balance: 6.013000000000, unlocked: 6.013000000000
Jan 24 22:44:52 ubuntu simplewallet[1839]: 2018-Jan-24 22:44:48.972023 [RPC0]HTTP [127.0.0.1] POST /json_rpc
Jan 24 22:44:52 ubuntu simplewallet[1839]: 2018-Jan-24 22:44:48.972101 [RPC0]/json_rpc[getbalance] processed with 0/0/0ms

**What does it mean? is it error or what?**
If we look at source code we can find function
void wallet2::pull_blocks(uint64_t start_height, size_t& blocks_added)

BOOST_FOREACH(auto& bl_entry, res.blocks)
  {
    cryptonote::block bl;
    r = cryptonote::parse_and_validate_block_from_blob(bl_entry.block, bl);
    THROW_WALLET_EXCEPTION_IF(!r, error::block_parse_error, bl_entry.block);

    crypto::hash bl_id = get_block_hash(bl);
    if(current_index >= m_blockchain.size())
    {
      process_new_blockchain_entry(bl, bl_entry, bl_id, current_index);
      ++blocks_added;
    }
    else if(bl_id != m_blockchain[current_index])
    {
      //split detected here !!!
      THROW_WALLET_EXCEPTION_IF(current_index == res.start_height, error::wallet_internal_error,
        "wrong daemon response: split starts from the first block in response " + string_tools::pod_to_hex(bl_id) +
        " (height " + std::to_string(res.start_height) + "), local block id at this height: " +
        string_tools::pod_to_hex(m_blockchain[current_index]));

      detach_blockchain(current_index);
      process_new_blockchain_entry(bl, bl_entry, bl_id, current_index);
    }
    else
    {
      **LOG_PRINT_L2("Block is already in blockchain: " << string_tools::pod_to_hex(bl_id));**
    }

What happens when we see this message? please advance me a bit!
Thank you.

**Comment by stoffu** [comment]
Any messages printed via `LOG_PRINT_L2` are just reports, not errors. You can safely ignore them.

**Comment by aeonix** [comment]
Resolved
