### ISSUE TITLE
c:\users\arno\documents\github\aeon-0.9.14.0\src\p2p\net_node.inl:328 UPNP_AddPortMapping failed.

### ISSUE THREAD

**Issue by sergeioryol** [aeonix/aeon-legacy#155]
how to correct?

**Comment by sergeioryol** [comment]
c:\users\arno\documents\github\aeon-0.9.14.0\src\p2p\net_node.inl:328 UPNP_AddPortMapping failed.

**Comment by ghost** [comment]
A few days ago I had the same error (OS: Linux Mint 18.3 x64). I'm trying to download the blockschain again, but the error repeats. Anyone can tell me if this is an important mistake?

**Comment by sergeioryol** [comment]
Hi. Nobody knows, it is important or not. We will hope that it isn't important

**Comment by DrStein99** [comment]
verified - same problem.

**Comment by iamsmooth** [comment]
UPNP is pretty unreliable and depends on your router settings, software bugs, etc. and not really necessary. If the error message bothers you then --no-igd (which disables UPNP altogether) should eliminate it. 

Its purpose is to open/forward the listening port in the router for incoming p2p connections. If you want that and UPNP doesn't work or is disabled you can forward the port manually in most routers.

**Comment by aeonix** [comment]
Resolved
