### ISSUE TITLE
Failed to create wallet

### ISSUE THREAD

**Issue by stream-sim** [aeonix/aeon-legacy#156]
This is my output from simplewallet binary:
```
aeon wallet v0.9.14.0()
Specify wallet file name (e.g., wallet.bin). If the wallet doesn't exist, it will be created.
Wallet file name: 
The wallet doesn't exist, generating new one
password: 
Error: failed to load wallet: file not found ".keys"
```

`aeond` is running and synchronized.

**Comment by aij** [comment]
What OS are you on?

Most do not allow the empty string as a filename, so I would guess you just need to enter a valid file name for whatever OS you're on.

**Comment by stream-sim** [comment]
I am on Ubuntu 16.04 LTS. Ok it works now when I add name and password. Thanks!
