### ISSUE TITLE
simplewallet allows export of spendkey and viewkey, but not import

### ISSUE THREAD

**Issue by alferz** [aeonix/aeon-legacy#157]
Just as the title says, a user can easily backup her spend and view keys but if she forgets to backup the mnemonic seed, her coins could be lost. Either remove ability to export keys, or introduce the ability to import them.

**Comment by stoffu** [comment]
>  but if she forgets to backup the mnemonic seed, her coins could be lost. 

This is not true. The mnemonic seed is just a different representation of the spend secret key whose size is 32 bytes. Although the current official CLI wallet (0.9.14) doesn't allow you to restore a wallet from a spend secret key, you can convert a spend secret key into its corresponding mnemonic seed using a JavaScript-based tool provided in [this website](https://xmr.llcoins.net/addressgen.html) (hosted by a Monero Core Team member luigi1111):

1. Paste your spend secret key to the field "2. Hexadecimal Seed".
2. Click "Gen 1."

The Aeon codebase is currently being rebased to the more recent codebase of Monero (pre-release is [here](https://github.com/stoffu/monero/releases/tag/v0.1.0)), and the new version will have an option `--generate-from-keys` which allows you to restore a wallet from a spend secret key.

**Comment by alferz** [comment]
Thanks stoffu for the link and I'm excited about the rebase! Its duplicative to the rebase obviously but since i had already finished work on it, i just created a pull request to add this functionality into the current legacy code in case there is a desire to add this functionally prior to the rebase release.

**Comment by iamsmooth** [comment]
There is a sufficient workaround for the legacy code as well as full support in the rebase so closing this issue and the associated PR.
