### ISSUE TITLE
Aeon's Equivalent of --disable-rpc-login

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [aeonix/aeon-legacy#160]
What's Aeon's equivalent of --disable-rpc-login?

**Comment by stoffu** [comment]
I don't think it's implemented. Meanwhile, the codebase is being rebased to more recent Monero, so this feature will surely be available in the next release: https://github.com/aeonix/aeon-rebase/pull/4

**Comment by TimeTravelersHackedMe** [comment]
@stoffu Thanks for the quick answer!

Another question: Can I bind the Wallet IP address so I can access it from another Docker container?

**Comment by stoffu** [comment]
I think so, via the `--rpc-bind-ip` flag, though this is a total guess since I'm not familiar with Docker at all.

**Comment by iamsmooth** [comment]
@TimeTravelersHackedMe AEON doesn't have rpc login at all so the option would have no purpose. If you enable RPC you are solely responsible for controlling access to the port or you will lose your coins, as discussed in the README.

This will be addressed in the same manner as Monero once the rebase code is released, as @stoffu noted.

**Comment by aeonix** [comment]
Resolved
