### ISSUE TITLE
P2P Port Firewall Settings

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [aeonix/aeon-legacy#163]
Do I have to do something with the p2p port to make Aeon sync properly? Is port 11180 required to be opened for Aeon to sync?

**Comment by stoffu** [comment]
No. If port 11180 is open, other nodes in the network can download blocks from you.

**Comment by TimeTravelersHackedMe** [comment]
So it's just for supporting the networks torrent?

**Comment by stoffu** [comment]
Yes, to support the P2P network ("torrent" isn't a correct term).

**Comment by aeonix** [comment]
Resolved
