### ISSUE TITLE
c++: internal compiler error

### ISSUE THREAD

**Issue by spidero** [aeonix/aeon-legacy#165]
root@iredmail:~/aeon# make
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   chrono
--   regex
--   serialization
--   program_options
--   atomic
-- Found Git: /usr/bin/git
-- Configuring done
-- Generating done
-- Build files have been written to: /root/aeon/build/release
cd build/release && make
make[1]: Entering directory '/root/aeon/build/release'
make[2]: Entering directory '/root/aeon/build/release'
make[3]: Entering directory '/root/aeon/build/release'
make[3]: Leaving directory '/root/aeon/build/release'
make[3]: Entering directory '/root/aeon/build/release'
fatal: No names found, cannot describe anything.
CMake Warning at src/version.cmake:3 (message):
  Cannot determine current revision.  Make sure that you are building either
  from a Git working tree or from a source archive.

make[3]: Leaving directory '/root/aeon/build/release'
[  0%] Built target version
make[3]: Entering directory '/root/aeon/build/release'
make[3]: Leaving directory '/root/aeon/build/release'
[ 11%] Built target libminiupnpc-static
make[3]: Entering directory '/root/aeon/build/release'
make[3]: Leaving directory '/root/aeon/build/release'
make[3]: Entering directory '/root/aeon/build/release'
[ 12%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/blockchain_storage.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
src/CMakeFiles/cryptonote_core.dir/build.make:230: recipe for target 'src/CMakeFiles/cryptonote_core.dir/cryptonote_core/blockchain_storage.cpp.o' failed
make[3]: *** [src/CMakeFiles/cryptonote_core.dir/cryptonote_core/blockchain_storage.cpp.o] Error 4
make[3]: Leaving directory '/root/aeon/build/release'
CMakeFiles/Makefile2:213: recipe for target 'src/CMakeFiles/cryptonote_core.dir/all' failed
make[2]: *** [src/CMakeFiles/cryptonote_core.dir/all] Error 2
make[2]: Leaving directory '/root/aeon/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/aeon/build/release'
Makefile:20: recipe for target 'build-release' failed
make: *** [build-release] Error 2

**Comment by aij** [comment]
> c++: **internal compiler error**: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> **See file:///usr/share/doc/gcc-5/README.Bugs for instructions**.

That is a bug in your compiler, not aeon. You might want to look at at the file it told you to look at for instructions on submitting a bug report... That will almost certainly include checking whether it's already been fixed in a newer version of GCC.

**Comment by iamsmooth** [comment]
It may be simply runing out of memory. Try increasing swap.

But in any case this is not an issue with AEON itself nor a general build problem on any common platform so this issue should be closed.
