### ISSUE TITLE
Comment out Multisig functions in new rebase wallet

### ISSUE THREAD

**Issue by pokech0p** [aeonix/aeon-legacy#168]
When testing I found that you can create a Multisig wallet but cannot send from it since RingCT is not enabled. I fear that many newcomers who are not familiar could potentially send aeon to a newly created AEON msig wallet but not be able to recover those funds. I was wondering if there was a way to disable msig related commands in the next release when incorporating Stoffu's rebase code?

thanks for your time, pokech0p

**Comment by stoffu** [comment]
It is already disabled: https://github.com/stoffu/monero/commit/68fab0ad33c11816edc2aed38e5cbff0aa66c70e

**Comment by pokech0p** [comment]
good deal, thanks

**Comment by aeonix** [comment]
Resolved
