### ISSUE TITLE
Don't read all block data into memory

### ISSUE THREAD

**Issue by HuiTurn** [aeonix/aeon-legacy#169]
what should I do?

**Comment by GeoSkyGPS** [comment]
Setup a swap file :)

**Comment by DeadManWalkingTO** [comment]
This is the worst part of node...
A node need a huge swap file...

**Comment by stoffu** [comment]
Or you could try the pre-release of the rebased code: https://github.com/stoffu/monero-core/releases/tag/v0.1.7.2

Source code is https://github.com/stoffu/monero/tree/aeon-rebase-new

**Comment by DeadManWalkingTO** [comment]
@stoffu Possible date for merge?

**Comment by stoffu** [comment]
No date decided yet, but early May is a possibility.

**Comment by aeonix** [comment]
No actual issue here, memory usage being addressed by rebase. Closing
