### ISSUE TITLE
How to restore Aeon wallet (cold storage)

### ISSUE THREAD

**Issue by joker419** [aeonix/aeon-legacy#170]
Hello :)

When I launch the simple wallet it asks for the file name but I have only my wallet with keys and I wish to restore the wallet stored on cold storage.

So  I launched "simplewallet" file, but when I put "--restore-deterministic-wallet", then fill in a password and it create me new memomnic 24 words ... 

Someone can help me please ?

Thank you very much.

**Comment by stoffu** [comment]
> but when I put "--restore-deterministic-wallet", then fill in a password and it create me new memomnic 24 words ...

I don't see how this can happen, because `--restore-deterministic--wallet` is supposed to ask you for the 24-word mnemonic seed, instead of creating it.

If you do not have the seed words but instead the spend secret key only, you could do the following:

- go to https://xmr.llcoins.net/addresstests.html and
- choose AEON from the drop-down menu at top left
- enter your spend secret key to "2. Hexadecimal Seed"
- press the button "Gen 1."

**Comment by joker419** [comment]
Thank you, I have the 24-word mnemonic seed that's not the problem. This is what I do, I launch simplewallet application, I get this automatically :

aeon wallet v0.9.14.0()
Specify wallet file name (e.g., wallet.bin). If the wallet doesn't exist, it will be created.
Wallet file name:

So maybe the good question is : 
Where I have to fill "--restore-deterministic--wallet" ? Maybe I do something wrong ? 
Thank you again :)

**Comment by stoffu** [comment]
Here's a usage example:
```
~$ ./simplewallet --restore-deterministic-wallet
aeon wallet v0.9.14.0()
Specify wallet file name (e.g., wallet.bin). If the wallet doesn't exist, it will be created.
Wallet file name: mytestwallet1
The wallet doesn't exist, generating new one
password: 
Specify electrum seed: pants sheet outside party liquid lazy fully glow evil bottle brush silently nice sword poor balance forth eternal press gift steady rich daughter test
Generated new wallet: WmtbPpJWBbEYvyHNJooTGri1b8Ftsd7GH8nG87XEMwmaFFUSeK4EQ2qbFobP9KRanT6uHX13KxQ2faranYW3UkFo32nrcttF2
view key: c63aa894111aa99e5abbea8656c941697abfff2c48479d3a00802fad47ece606
**********************************************************************
Your wallet has been generated.
To start synchronizing with the daemon use "refresh" command.
Use "help" command to see the list of available commands.
Always use "exit" command when closing simplewallet to save
current session's state. Otherwise, you will possibly need to synchronize 
your wallet again. Your wallet key is NOT under risk anyway.


PLEASE NOTE: the following 24 words can be used to recover access to your wallet. Please write them down and store them somewhere safe and secure. Please do not store them in your email or on file storage services outside of your immediate control.

pants sheet outside party liquid lazy fully glow evil bottle brush silently nice sword poor balance forth eternal press gift steady rich daughter test 
**********************************************************************
[wallet WmtbPp]: exit
~$ ls
mytestwallet1
mytestwallet1.address.txt
mytestwallet1.keys
```

**Comment by joker419** [comment]
I really do not understand ... when I launch the simplewallet application, the begin of the block is : 

aeon wallet v0.9.14.0()
Specify wallet file name (e.g., wallet.bin). If the wallet doesn't exist, it will be created.
Wallet file name:

Where fill in the "--restore-deterministic--wallet" so ? 

Thank you again.

**Comment by stoffu** [comment]
> Where fill in the "--restore-deterministic--wallet" so ?

I'm afraid your English isn't grammatically correct and I can't get what you're asking.

Perhaps, you use Windows and start the program by simply double-clicking `simplewallet.exe`? If so, that won't work, and you need to open the Command Prompt and execute `simplewallet.exe` from the command line with `--restore-deterministic-wallet` as the command line argument.

**Comment by joker419** [comment]
Ok I am sorry for the english if it is not understanding as you wish ;)

Yes I use windows and I tryed to do with your advice, but I get the same problem.
You can see below what I am getting : 

Microsoft Windows [version 10.0.16299.309]
(c) 2017 Microsoft Corporation. Tous droits réservés.

C:\Users\Utilisateur>simplewallet.exe
aeon wallet v0.9.14.0()
Specify wallet file name (e.g., wallet.bin). If the wallet doesn't exist, it will be created.
Wallet file name: --restore-deterministic-wallet
password:

**Comment by joker419** [comment]
Is it the only method we have to restore an aeon wallet on cold storage ?

**Comment by joker419** [comment]
Thanks The problem is solved :)

**Comment by stoffu** [comment]
I’ve never imagined such a usage:) 
As you know now, the correct syntax is

    simplewallet.exe --restore-deterministic-wallet
