### ISSUE TITLE
0.9.6.0 Failed make on Ubuntu 16.04.1 x64

### ISSUE THREAD

**Issue by Crypt0-Bear** [aeonix/aeon-legacy#37]
Attempted to build release 0.9.6.0 on Ubuntu 16.04.1 x64. 

Added dependencies:
sudo apt-get install cmake g++ libboost-all-dev

Might be missing a dependency ? 
 
Ran make 
-- Build files have been written to: /mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release
cd build/release && make
make[1]: Entering directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
make[2]: Entering directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
make[3]: Entering directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
Scanning dependencies of target version
make[3]: Leaving directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
make[3]: Entering directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
fatal: Not a git repository (or any parent up to mount point /mnt/volume-nyc1-01)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Warning at src/version.cmake:3 (message):
  Cannot determine current revision.  Make sure that you are building either
  from a Git working tree or from a source archive.

make[3]: Leaving directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
[  0%] Built target version
make[3]: Entering directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
Scanning dependencies of target upnpc-static
make[3]: Leaving directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
make[3]: Entering directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
[  1%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/igd_desc_parse.c.o
[  2%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/miniupnpc.c.o
[  3%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/minixml.c.o
[  4%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/minisoap.c.o
[  5%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/miniwget.c.o
[  5%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/upnpc.c.o
[  6%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/upnpcommands.c.o
[  7%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/upnpreplyparse.c.o
[  8%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/upnperrors.c.o
[  9%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/connecthostport.c.o
[ 10%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/portlistingparse.c.o
[ 10%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/receivedata.c.o
[ 11%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/minissdpc.c.o
[ 12%] Linking C static library libminiupnpc.a
make[3]: Leaving directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
[ 12%] Built target upnpc-static
make[3]: Entering directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
Scanning dependencies of target common
make[3]: Leaving directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
make[3]: Entering directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
[ 12%] Building CXX object src/CMakeFiles/common.dir/common/base58.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
src/CMakeFiles/common.dir/build.make:62: recipe for target 'src/CMakeFiles/common.dir/common/base58.cpp.o' failed
make[3]: *** [src/CMakeFiles/common.dir/common/base58.cpp.o] Error 4
make[3]: Leaving directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
CMakeFiles/Makefile2:403: recipe for target 'src/CMakeFiles/common.dir/all' failed
make[2]: *** [src/CMakeFiles/common.dir/all] Error 2
make[2]: Leaving directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/mnt/volume-nyc1-01/aeon-source/aeon-0.9.6.0/build/release'
Makefile:20: recipe for target 'build-release' failed
make: *** [build-release] Error 2

**Comment by sammy007** [comment]
Looks like OS killed compiler process, make sure you have enough RAM and swap?

**Comment by aeonix** [comment]
Assumed resolved by above. If not please reopen
