### ISSUE TITLE
Can't sync : Block verification failed

### ISSUE THREAD

**Issue by 1towia** [aeonix/aeon-legacy#42]
Hi, I'm trying to sync but the process stuck at block height 798358/798359. I tried several times and the same problems occur.

There is a lot of errors in the aeond.log : http://pastebin.com/LiBBWPBv

These errors :
```
2017-Mar-02 16:08:33.786044 [P2P5]Block with id: <72dc340601a863973fc1b818a554b1cbff6fdde317ad675dacfb125d88b1814d>have at least one unknown transaction with id: <2d1f88a0c67ca908695abd69dcd97c3039dee0041ce013df7f946dfe1d6bf73c>
2017-Mar-02 16:08:33.786509 [P2P5][5.9.102.108:11180 OUT]Block verification failed, dropping connection
```

Then :
```
2017-Mar-02 16:10:13.096962 [P2P2]----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 798358
id: <72dc340601a863973fc1b818a554b1cbff6fdde317ad675dacfb125d88b1814d>
PoW:    <f570bebd911eeba5817a1770ad16ab3d30ab8616702813bd60193a7b06000000>
difficulty: 320369628
```

And :
```
2017-Mar-02 16:10:18.978448 [P2P2]ERROR /root/aeon/src/cryptonote_core/blockchain_storage.cpp:783 alternative chain have wrong connection to main chain
2017-Mar-02 16:10:18.978885 [P2P2]Block recognized as orphaned and rejected, id = <e542a4be58bd653e989c0b21409681c39db05d45c46807e60cb6924c7f935c06>
2017-Mar-02 16:10:18.979185 [P2P2][178.63.72.22:11180 OUT]Block received at sync phase was marked as orphaned, dropping connection
```

edit:
It seems that the block 798358 have a strange transaction in it.
tx hash : 
86358f3aecbb5a1e5319bb0b771dd7bc139d043adab6a63d8c1577e74157c760
The global indexes are all 0 :

http://chainradar.com/aeon/transaction/86358f3aecbb5a1e5319bb0b771dd7bc139d043adab6a63d8c1577e74157c760
http://chainradar.com/aeon/block/798358

**Comment by iamsmooth** [comment]
being investigated thanks

**Comment by gosha12** [comment]
the same mistake, I cannot synchronize a purse

`2017-Mar-03 11:51:12.215414 [P2P6]Block with id: <72dc340601a863973fc1b818a554b1cbff6fdde317ad675dacfb125d88b1814d>have at least one unknown transaction with id: <2d1f88a0c67ca908695abd69dcd97c3039dee0041ce013df7f946dfe1d6bf73c>
2017-Mar-03 11:51:12.231014 [P2P6][5.9.69.142:40838 INC]Block verification failed, dropping connection
2017-Mar-03 11:51:12.231014 [P2P6]Ip 5.9.69.142 blocked.`

**Comment by Congabonga** [comment]
Happening here too. Cannot get past block 798363.

```
SYNCHRONIZATION started
2017-Mar-03 09:39:54.528452 [P2P7]Block recognized as orphaned and rejected, id = <2632f348d1f895a708b992fe0116b8069285b4ec26fdbc1443987a729dc25443>
2017-Mar-03 09:39:54.528452 [P2P7][98.238.231.31:50364 INC]Block received at sync phase was marked as orphaned, dropping connection
2017-Mar-03 09:39:55.684765 [P2P7]Block recognized as orphaned and rejected, id = <2632f348d1f895a708b992fe0116b8069285b4ec26fdbc1443987a729dc25443>
2017-Mar-03 09:39:55.684765 [P2P7][91.152.122.132:48442 INC]Block received at sync phase was marked as orphaned, dropping connection
2017-Mar-03 09:39:55.919177 [P2P7][98.238.231.31:50394 INC]Sync data returned unknown top block: 798363 -> 798772 [409 blocks (1 days) behind]
SYNCHRONIZATION started
2017-Mar-03 09:39:57.544262 [P2P1][91.152.122.132:48444 INC]Sync data returned unknown top block: 798363 -> 798772 [409 blocks (1 days) behind]
SYNCHRONIZATION started
2017-Mar-03 09:40:00.419392 [P2P7]Block recognized as orphaned and rejected, id = <2632f348d1f895a708b992fe0116b8069285b4ec26fdbc1443987a729dc25443>
2017-Mar-03 09:40:00.435013 [P2P7][91.152.122.132:48444 INC]Block received at sync phase was marked as orphaned, dropping connection
2017-Mar-03 09:40:00.700651 [P2P1]Block recognized as orphaned and rejected, id = <2632f348d1f895a708b992fe0116b8069285b4ec26fdbc1443987a729dc25443>
2017-Mar-03 09:40:00.716275 [P2P1][98.238.231.31:50394 INC]Block received at sync phase was marked as orphaned, dropping connection
2017-Mar-03 09:40:00.716275 [P2P1]Ip 98.238.231.31 blocked.
2017-Mar-03 09:40:01.747608 [P2P7][91.152.122.132:48446 INC]Sync data returned unknown top block: 798363 -> 798772 [409 blocks (1 days) behind]
SYNCHRONIZATION started
2017-Mar-03 09:40:02.435121 [P2P7]Block recognized as orphaned and rejected, id = <2632f348d1f895a708b992fe0116b8069285b4ec26fdbc1443987a729dc25443>
2017-Mar-03 09:40:02.450745 [P2P7][91.152.122.132:48446 INC]Block received at sync phase was marked as orphaned, dropping connection
2017-Mar-03 09:40:03.935222 [P2P7][91.152.122.132:48448 INC]Sync data returned unknown top block: 798363 -> 798772 [409 blocks (1 days) behind]
SYNCHRONIZATION started
2017-Mar-03 09:40:04.638363 [P2P1]Block recognized as orphaned and rejected, id = <2632f348d1f895a708b992fe0116b8069285b4ec26fdbc1443987a729dc25443>
2017-Mar-03 09:40:04.653984 [P2P1][91.152.122.132:48448 INC]Block received at sync phase was marked as orphaned, dropping connection
```

**Comment by iamsmooth** [comment]
Here is an update https://bitcointalk.org/index.php?topic=641696.msg18047243#msg18047243

There is a serious (old) bug in the blockchain code. I'm working on finalizing a fix.

**Comment by billaue2** [comment]
As I saw at http://chainradar.com/aeon/block/798358 , the mentioned block is still valid and my mining pool (http://aeon.sumominer.com) is still running without any problem so I'm not sure what really happened. Also, I don't think it's easy to roll back to a bypass block leaving all miner's transactions invalid though a fix is of course necessary. So can you release a hardfork that marks and force-adds the block 798358 (Monero did the same for another bug, if I remember correctly)?

**Comment by Aidess** [comment]
My mining pool (http://aeon.rupool.tk) running

**Comment by billaue2** [comment]
Meanwhile, anyone who has sync problem can download the (nearly) latest blockchain snapshot from here http://aeon.sumominer.com/download/aeon_blockchain.tar.gz2 (Linux only)

**Comment by iamsmooth** [comment]
> So can you release a hardfork that marks and force-adds the block 798358 (Monero did the same for another bug, if I remember correctly)?

Unfortunately no. The nature of the issue is different. In this case the block has been accepted by nodes but the data store is in an invalid state. While your node (as with others) appears to have accepted the block, they didn't do so correctly.

As things stand now, the blocks stored in the node database at height 798358 are invalid because they are missing a transaction. They can't be part of a valid chain and were only accepted due to a bug in the software which has now been corrected causing them to be correctly rejected. The transaction that appears to be present in that block is actually a different one (txid does not match the block header)

Without extensive analysis it is impossible to know what problems this may cause for subsequent blocks. To undertake such analysis would take an indefinite time and if it turned out that rejecting the invalid chain were still necessary we would be left with an even larger amount of blocks to rejected.

**Comment by iamsmooth** [comment]
This issue has been resolved by release 0.9.8.0. Please update all nodes ASAP.

https://github.com/aeonix/aeon/releases/tag/v0.9.8.0

As mentioned in the update notice linked above, I will accept well-documented claims for reimbursement from the development fund if you have mined blocks on the invalidated chain or otherwise lost coins. There is no other feasible solution.

**Comment by billaue2** [comment]
Interesting case in term of concesus. We'll need 51% hash power to make this happen, right?

**Comment by Aidess** [comment]
```
2017-Mar-04 12:52:35.582504 ERROR /aeon_0.9.8.0/src/cryptonote_core/checkpoints.cpp:71 CHECKPOINT FAILED FOR HEIGHT 798358. EXPECTED HASH: <804c7fe07511d9387e7cda534c9e8b644d406d8d0ff299799a8177850d4e75a0>, FETCHED HASH: <72dc340601a863973fc1b818a554b1cbff6fdde317ad675dacfb125d88b1814d>
2017-Mar-04 12:52:35.582561 ERROR /aeon_0.9.8.0/src/cryptonote_core/blockchain_storage.cpp:99 checkpoint fail, blockchain.bin invalid
2017-Mar-04 12:52:35.582580 ERROR /aeon_0.9.8.0/src/cryptonote_core/cryptonote_core.cpp:128 Failed to initialize blockchain storage
2017-Mar-04 12:52:35.582602 ERROR /aeon_0.9.8.0/src/daemon/daemon.cpp:190 Failed to initialize core

```
It is evident need to re-sync  blockchain

**Comment by iamsmooth** [comment]
> We'll need 51% hash power to make this happen, right?

In a sense yes. The corrected code will not recognize the existing chain^1 so to people running the new code, the miners still on the other chain simply don't exist. They might as well be mining another coin. However, there is nothing to prevent people from continuing to use the old code and they would only switch to the new chain if it has >50% hash power. I have no idea what the eventual outcome of the data store corruption might be. Perhaps it could be okay, perhaps not? 

^1 for two reasons, one being the checkpoint that @Aidess just noted (which I mostly added to force a resync) but even if you take out that checkpoint you will see that the corrected validation code still rejects the block.

**Comment by billaue2** [comment]
The danger of using old codes is that it may introduce more invalid blocks and one day old blockchain would be no longer sync, so I'll go with new codes. Luckily, my pool is nearly half of hash power but I'll be happy if other pools will do the same, especially the Minergate guys, to make sure the network won't be screwed up. Anyone else can confirm?

**Comment by Aidess** [comment]
I'm updating

**Comment by billaue2** [comment]
@iamsmooth Another concern is if the exchanges like Bittrex, Changelly etc. are still using old blockchain they may lost money and miners who mine on hard-forked blockchain cannot sell AEON there. Do you have any contact to send notice to them?

**Comment by Aidess** [comment]
![image](https://cloud.githubusercontent.com/assets/26172936/23578662/57b156ce-00ed-11e7-9cff-d179435737df.png)
Here it is after synchronization

```
2017-Mar-04 12:54:43.213599 Starting...
2017-Mar-04 12:54:43.213978 aeon v0.9.8.0()
2017-Mar-04 12:54:43.214047 Module folder: ./aeond
2017-Mar-04 12:54:43.214286 Initializing p2p server...
2017-Mar-04 12:54:43.214517 Binding on 0.0.0.0:11180
2017-Mar-04 12:54:43.214623 Net service binded on 0.0.0.0:11180
2017-Mar-04 12:54:43.214667 Attempting to add IGD port mapping.
2017-Mar-04 12:54:44.273248 ERROR /home/aeon/aeon_0.9.8.0/src/p2p/net_node.inl:322 UPNP_AddPortMapping failed.
2017-Mar-04 12:54:44.273369 P2p server initialized OK
2017-Mar-04 12:54:44.273413 Initializing cryptonote protocol...
2017-Mar-04 12:54:44.273451 Cryptonote protocol initialized OK
2017-Mar-04 12:54:44.273483 Initializing core rpc server...
2017-Mar-04 12:54:44.273524 Binding on 127.0.0.1:11181
2017-Mar-04 12:54:44.273679 Core rpc server initialized OK on port: 11181
2017-Mar-04 12:54:44.273737 Initializing core...
2017-Mar-04 12:54:44.273809 Loading blockchain...
2017-Mar-04 12:54:44.273872 Can't load blockchain storage from file, generating genesis block.
2017-Mar-04 12:54:44.305974 Blockchain initialized. last block: 0, d1704.h4.m54.s44 time ago, current difficulty: 1
2017-Mar-04 12:54:44.306055 Core initialized OK
2017-Mar-04 12:54:44.306144 Starting core rpc server...
2017-Mar-04 12:54:44.306175 Run net_service loop( 2 threads)...
2017-Mar-04 12:54:44.306260 [SRV_MAIN]Core rpc server started ok
2017-Mar-04 12:54:44.306287 [SRV_MAIN]Starting p2p net loop...
2017-Mar-04 12:54:44.306323 [SRV_MAIN]Run net_service loop( 10 threads)...
2017-Mar-04 12:54:45.306448 [P2P1]
**********************************************************************
The daemon will start synchronizing with the network. It may take up to several hours.

You can set the level of process detailization* through "set_log <level>" command*, where <level> is between 0 (no details) and 4 (very verbose).

Use "help" command to see the list of available commands.

Note: in case you need to interrupt the process, use "exit" command. Otherwise, the current progress won't be saved.
**********************************************************************
2017-Mar-04 12:54:54.290236 [P2P6][76.94.82.0:11180 OUT]Sync data returned unknown top block: 1 -> 174850 [174849 blocks behind] 
SYNCHRONIZATION started
2017-Mar-04 12:54:57.514419 [P2P1]CHECKPOINT PASSED FOR HEIGHT 1 <1440a20f078bf3264822234b347f8382606577d73d4e9d3cb7296d73889bc421>
2017-Mar-04 12:54:57.527430 [P2P1]CHECKPOINT PASSED FOR HEIGHT 100 <6dd13aaab16679f49ee6b2b75c7dc99b1fd09ab2282b18cb4b55b73110655742>
2017-Mar-04 12:54:59.511149 [P2P7][5.9.60.176:11180 OUT]Sync data returned unknown top block: 201 -> 799181 [798980 blocks behind] 
SYNCHRONIZATION started
2017-Mar-04 12:54:59.725257 [P2P4][5.9.63.70:11180 OUT]Sync data returned unknown top block: 201 -> 799181 [798980 blocks behind] 
SYNCHRONIZATION started
2017-Mar-04 12:55:06.923829 [P2P6][74.91.23.186:11180 OUT]Sync data returned unknown top block: 401 -> 119792 [119391 blocks behind] 
SYNCHRONIZATION started
2017-Mar-04 12:55:18.078792 [P2P7][88.198.24.164:11180 OUT]Sync data returned unknown top block: 401 -> 799181 [798780 blocks behind] 
SYNCHRONIZATION started
2017-Mar-04 12:55:18.567133 [P2P9][5.9.69.142:11180 OUT]Sync data returned unknown top block: 401 -> 799181 [798780 blocks behind] 
SYNCHRONIZATION started
2017-Mar-04 12:55:24.200659 [P2P2][37.193.137.154:11180 OUT]Sync data returned unknown top block: 401 -> 798363 [797962 blocks behind] 
SYNCHRONIZATION started
2017-Mar-04 12:55:24.824728 [P2P1][46.167.243.253:11180 OUT]Sync data returned unknown top block: 401 -> 595849 [595448 blocks behind] 
SYNCHRONIZATION started
2017-Mar-04 12:56:39.616697 [P2P3]CHECKPOINT PASSED FOR HEIGHT 1000 <bc6458452fd0575a314089bf302f6fd68ebaa2d689c42f3365293b96bbdf1f25>
2017-Mar-04 12:57:47.039781 [P2P9][148.251.51.113:7080 OUT]Sync data returned unknown top block: 7001 -> 799183 [792182 blocks behind] 
SYNCHRONIZATION started
2017-Mar-04 12:58:20.250595 [P2P6]CHECKPOINT PASSED FOR HEIGHT 10000 <1ac1ebd25baf0d6ec593daa3389f1aa7e860ff2cc29f3cf1be586d245b379da4>
2017-Mar-04 12:59:58.850554 [P2P7]CHECKPOINT PASSED FOR HEIGHT 15000 <15567af42afc1ed00538f53b5e3822d421e3ed6372ca79f4ea4e3e3bab709a87>
save
2017-Mar-04 13:26:56.853252 Storing blockchain...
2017-Mar-04 13:27:08.023490 Blockchain stored OK.
save
2017-Mar-04 13:30:00.840035 Storing blockchain...
2017-Mar-04 13:30:13.106713 Blockchain stored OK.
2017-Mar-04 13:31:08.539422 [P2P8]CHECKPOINT PASSED FOR HEIGHT 175500 <3f7dd748b3b863b04654d87a387f2b65a365f467188971f3192eab2368e64a35>
save
2017-Mar-04 13:37:11.802445 Storing blockchain...
2017-Mar-04 13:37:26.247192 Blockchain stored OK.
save
2017-Mar-04 13:43:20.124062 Storing blockchain...
2017-Mar-04 13:43:36.700297 Blockchain stored OK.
2017-Mar-04 13:45:57.745990 [P2P5]CHECKPOINT PASSED FOR HEIGHT 450000 <f69a6e57c4dd5df2f492c9d31c50f11aad2c25a64d540ce5f5d11b572aec8ab7>
save
2017-Mar-04 13:50:08.742853 Storing blockchain...
2017-Mar-04 13:50:27.976054 Blockchain stored OK.
2017-Mar-04 13:53:13.255642 [P2P7]CHECKPOINT PASSED FOR HEIGHT 540000 <94e19cf9d5a16ae90f67c321f8376b87da21d6d6c2cb0957b9ab558dca66c1dc>
2017-Mar-04 13:57:52.658402 [P2P6]CHECKPOINT PASSED FOR HEIGHT 592001 <e8bc936b287a9c426a15cf127624b064c88e6d37655cc87f9a62cf1623c62385>
save
2017-Mar-04 14:08:24.987000 Storing blockchain...
2017-Mar-04 14:08:49.813655 Blockchain stored OK.
2017-Mar-04 14:10:03.837688 [P2P7][46.167.243.253:11180 OUT] SYNCHRONIZED OK
2017-Mar-04 14:10:03.837818 [P2P7]
**********************************************************************
You are now synchronized with the network. You may now start simplewallet.

Please note, that the blockchain will be saved only after you quit the daemon with "exit" command or if you use "save" command.
Otherwise, you will possibly need to synchronize the blockchain again.

Use "help" command to see the list of available commands.
**********************************************************************
save
2017-Mar-04 14:12:03.748514 Storing blockchain...
2017-Mar-04 14:12:28.928001 Blockchain stored OK.
2017-Mar-04 14:16:37.025701 [P2P0][176.9.117.76:11180 OUT]Sync data returned unknown top block: 739061 -> 799202 [60141 blocks (167 days) behind] 
SYNCHRONIZATION started
2017-Mar-04 14:19:10.547773 [P2P7][5.9.101.245:11180 OUT]Sync data returned unknown top block: 740495 -> 798363 [57868 blocks (160 days) behind] 
SYNCHRONIZATION started
2017-Mar-04 14:19:31.043228 [P2P7][176.9.117.76:11180 OUT]Sync data returned unknown top block: 742910 -> 799202 [56292 blocks (156 days) behind] 
SYNCHRONIZATION started
2017-Mar-04 14:19:37.354177 [P2P7][91.210.26.205:11180 OUT]Sync data returned unknown top block: 744095 -> 799202 [55107 blocks (153 days) behind] 
SYNCHRONIZATION started
2017-Mar-04 14:19:39.421939 [P2P0][120.25.64.28:11180 OUT]Sync data returned unknown top block: 744695 -> 799202 [54507 blocks (151 days) behind] 
SYNCHRONIZATION started
2017-Mar-04 14:22:25.601304 [RPC0]----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 778088
id:	<89949b380cdcdb34b82964886b05b1ece71dc74a465b145662b0844ff90f2c85>
PoW:	<6232b8412186e65686bb1c0bb9467b58e6dbe2e5b5b92a0e7a0e453110000000>
difficulty:	204571379
2017-Mar-04 14:24:58.138588 [P2P7]ERROR /home/aeon/aeon_0.9.8.0/src/cryptonote_core/checkpoints.cpp:71 CHECKPOINT FAILED FOR HEIGHT 798358. EXPECTED HASH: <804c7fe07511d9387e7cda534c9e8b644d406d8d0ff299799a8177850d4e75a0>, FETCHED HASH: <72dc340601a863973fc1b818a554b1cbff6fdde317ad675dacfb125d88b1814d>
2017-Mar-04 14:24:58.138667 [P2P7]ERROR /home/aeon/aeon_0.9.8.0/src/cryptonote_core/blockchain_storage.cpp:1585 CHECKPOINT VALIDATION FAILED
2017-Mar-04 14:24:58.138693 [P2P7][176.9.117.76:11180 OUT]Block verification failed, dropping connection
2017-Mar-04 14:24:59.697152 [P2P4][78.46.139.6:11180 OUT]Sync data returned unknown top block: 798358 -> 799204 [846 blocks (2 days) behind] 
SYNCHRONIZATION started
2017-Mar-04 14:25:00.424115 [P2P2]ERROR /home/aeon/aeon_0.9.8.0/src/cryptonote_core/checkpoints.cpp:71 CHECKPOINT FAILED FOR HEIGHT 798358. EXPECTED HASH: <804c7fe07511d9387e7cda534c9e8b644d406d8d0ff299799a8177850d4e75a0>, FETCHED HASH: <72dc340601a863973fc1b818a554b1cbff6fdde317ad675dacfb125d88b1814d>
2017-Mar-04 14:25:00.424206 [P2P2]ERROR /home/aeon/aeon_0.9.8.0/src/cryptonote_core/blockchain_storage.cpp:1585 CHECKPOINT VALIDATION FAILED
2017-Mar-04 14:25:00.424244 [P2P2][78.46.139.6:11180 OUT]Block verification failed, dropping connection
2017-Mar-04 14:25:02.406433 [P2P5][24.220.78.231:11180 OUT]Sync data returned unknown top block: 798358 -> 798363 [5 blocks (0 days) behind] 
SYNCHRONIZATION started
2017-Mar-04 14:25:02.770027 [P2P9]ERROR /home/aeon/aeon_0.9.8.0/src/cryptonote_core/checkpoints.cpp:71 CHECKPOINT FAILED FOR HEIGHT 798358. EXPECTED HASH: <804c7fe07511d9387e7cda534c9e8b644d406d8d0ff299799a8177850d4e75a0>, FETCHED HASH: <72dc340601a863973fc1b818a554b1cbff6fdde317ad675dacfb125d88b1814d>
2017-Mar-04 14:25:02.770124 [P2P9]ERROR /home/aeon/aeon_0.9.8.0/src/cryptonote_core/blockchain_storage.cpp:1585 CHECKPOINT VALIDATION FAILED
2017-Mar-04 14:25:02.770169 [P2P9][91.210.26.205:11180 OUT]Block verification failed, dropping connection
2017-Mar-04 14:25:03.874075 [P2P4]CHECKPOINT PASSED FOR HEIGHT 798358 <804c7fe07511d9387e7cda534c9e8b644d406d8d0ff299799a8177850d4e75a0>
2017-Mar-04 14:25:04.017275 [P2P4][24.220.78.231:11180 OUT] SYNCHRONIZED OK
2017-Mar-04 14:25:04.630874 [P2P9][78.46.139.6:11180 OUT]Sync data returned unknown top block: 798363 -> 799204 [841 blocks (2 days) behind] 
SYNCHRONIZATION started
2017-Mar-04 14:25:05.361676 [P2P2]Block with id: <72dc340601a863973fc1b818a554b1cbff6fdde317ad675dacfb125d88b1814d>
 can't be accepted for alternative chain, block height: 798358
 blockchain height: 798363
2017-Mar-04 14:25:05.361771 [P2P2][120.25.64.28:11180 OUT]Block verification failed, dropping connection
2017-Mar-04 14:25:05.508676 [P2P1]Block with id: <72dc340601a863973fc1b818a554b1cbff6fdde317ad675dacfb125d88b1814d>
 can't be accepted for alternative chain, block height: 798358
 blockchain height: 798363
2017-Mar-04 14:25:05.508807 [P2P1][78.46.139.6:11180 OUT]Block verification failed, dropping connection
2017-Mar-04 14:25:10.747426 [P2P3][5.9.145.6:11180 OUT]Sync data returned unknown top block: 798363 -> 799204 [841 blocks (2 days) behind] 
SYNCHRONIZATION started
2017-Mar-04 14:25:12.339192 [P2P5]Block with id: <72dc340601a863973fc1b818a554b1cbff6fdde317ad675dacfb125d88b1814d>
 can't be accepted for alternative chain, block height: 798358
 blockchain height: 798363
2017-Mar-04 14:25:12.339251 [P2P5][5.9.145.6:11180 OUT]Block verification failed, dropping connection

```

**Comment by billaue2** [comment]
I think that's why we'll need majority to upgrade to reach consensus. I still need more confirmation from other pools, maybe my final decision will come on Monday.

**Comment by sammy007** [comment]
> I still need more confirmation from other pools

What consensus you wanna reach here? You either don't understand wtf you are doing or just trying to troll us here. There is emergency hard fork, you either support it or you are running yet another "classic" and wasting your customers money.

**Comment by billaue2** [comment]
Wtf here is the blockc

**Comment by billaue2** [comment]
Trolling? Thanks, you just gave me the idea to run "classic" version while seeking for better solution. Maybe. :$

**Comment by billaue2** [comment]
Sorry for not in good mood now. After thought, I'll go with new fork only if major exchanges accept it and the compensation for miners is clear. So, I'll need a bit more time for sure.

**Comment by sammy007** [comment]
Time to decide what? To go with corrupted blockchain or with correct chain? All exchanges aware of problems and suspended withdrawals and deposits long ago. Miners are always at risk like all users of experimental software, i vote against bail-out for miners because both miners and pool ops must be responsible, follow repository notifications, follow development. it's not `set and forget` business.

**Comment by notsuhz** [comment]
aeon.kryptopool.com has been updated to 0.9.8.0

**Comment by quangvu3** [comment]
i'm a miner and although the rollback won't cost me a fortune, i don't like that at all. i hardly remember a case that blockchain has to rollback and it's also different case of ETH vs ETC. 

P/s i don't like @sammy007 attitude that pass all responsibility to miners. i think only a few loyal miners make AEON still alive although the proj had been almost abandoned for months and this not a good sign :(

**Comment by iamsmooth** [comment]
@sammy007 miners did nothing wrong from the time of the original problem until the first announcement of trouble and likely chain corruption several hours later. However, after that I agree it was a responsibility to decide to stay informed and decide what to do

Original announcement that was linked here above:
> Unfortunately it looks like there is going to need to be a rollback to block 798358. I do not recommend making any further transactions at this time until after the fix.
> 
> Coins that you sent since block 798358 will be returned to you if you rescan your wallet after the fix. If you received coins after block 798358 they will be lost unless you get the sender to resend them. This is unfortunate, but it is the nature of experimental blockchain software. I will consider reimbursement from the development fund if anyone wants to make a well-supported claim.

@billaue2 bitttrex, crytpopia have all been notified. Both suspended wallet transactions when told of the original problem. I'm not sure of contact information for changelly. If someone has contact info please contact them or pass it to me.

@quangvhg I agree with you people who have stuck with this coin when the original developer abandoned it and it was worth nothing to almost nothing for a long time deserve our respect. I understand the frustration of 'wasted' mining but I would ask that everyone pull together and try to restore things to normal asap. Trying to stick with a broken chain makes no sense and would destroy trust when it very easily could break again, and in a worse manner.

We are in the process of rebasing to the Monero code which, while it has its own potential problems (nothing is guaranteed error free) is much more actively developed and tested. Let's pull together, move forward past this frustrating (for everyone) event, and continue building the community and the coin.

**Comment by billaue2** [comment]
Thank @iamsmooth, I'm on the way to new fork now. I agree that we'll have to move forward and build better community.

My pool is shutdown now, all miners are redirected to  aeon.kryptopool.com @suhz

**Comment by Aidess** [comment]
As a result, about 1,000 coins disappeared from the reserve to the pool

**Comment by billaue2** [comment]
@Aidess our miners would have about 7k coins missed, and  http://aeon.sumomier.com now has a brand new start

**Comment by iamsmooth** [comment]
Hi, all

Unfortunately I still see a problem with the data store. It looks like there is going to need to be another fix which may or may not invalidate blocks. I don't know yet and I'm on a plane right now so I can't analyze it right away.

Will follow up soon.

**Comment by iamsmooth** [comment]
preliminary analysis does not show a problem but i will be doing some further tests. for now i believe the new release and data store or are okay. that is not a guarantee, just my best opinion

**Comment by iamsmooth** [comment]
After some more investigation I don't see any problem. I was misreading the output of one of the daemon commands. Sorry for the false alarm. I'll continue to keep an eye on things but at this moment it looks like everything is working correctly.

**Comment by Aidess** [comment]
@billaue2 But I also started my pool http://aeon.rupool.tk

**Comment by iamsmooth** [comment]
Hello all. Looks like the problem may not yet be completely solved. I've added some additional sanity checks to my development version of the code which tripped possibly indicating more closely the source of the issue and I'm working to resolve it. At this point I can only advise to be careful and await further announcements.

EDIT: clarify that the suspicious output may _or may not_ be evidence of a problem (not yet determined)

**Comment by Aidess** [comment]
```
2017-Mar-09 15:07:28.643379 [P2P9][138.201.21.7:58425 INC]Sync data returned unknown top block: 800432 -> 798359 [2073 blocks (-5 days) ahead] 
SYNCHRONIZATION started
2017-Mar-09 15:07:29.031796 [P2P1]ERROR /aeon-0.9.8.0/src/cryptonote_protocol/cryptonote_protocol_handler.inl:362 [138.201.21.7:58425 INC]sent wrong NOTIFY_RESPONSE_GET_OBJECTS: block with id=6ac6ec217c69ca0f535ae5acaa2225d1d9a55fd01813cd752d1a399404c32dfc, tx_hashes.size()=2 mismatch with block_complete_entry.m_txs.size()=0, dropping connection
```

**Comment by iamsmooth** [comment]
@Aidess the peer is sending invalid data when syncing, which your node is rejecting. That by itself is nor harmful but clutters the log message and I'll be adding that missing ban case in the new update.

**Comment by sskyspear** [comment]
2017-Dec-03 12:22:53.681802 [P2P3]Block with id: <9135f7c24d67fc7ad618e231ce2d38f59307b50ae2b23e3aa8640f02aebf0f45>
 can't be accepted for alternative chain, block height: 406
 blockchain height: 45198
2017-Dec-03 12:22:53.697428 [P2P3][88.162.4.146:11180 OUT]Block verification failed, dropping connection
2017-Dec-03 12:25:40.579879 [P2P1][sock 788] Some problems at write: ╙фрыхээ√щ їюёЄ яЁшэєфшЄхы№эю ЁрчюЁтры ёє∙хёЄтє■∙хх яюфъы■ўхэшх:10054
2017-Dec-03 12:25:42.395309 [P2P2][74.73.146.248:11180 OUT]Sync data returned unknown top block: 54320 -> 897435 [843115 blocks behind]
SYNCHRONIZATION started

**Comment by iamsmooth** [comment]
@sskyspear This is not a problem. It means the other node has an invalid chain. (I believe someone tried to create a fork or something and mined starting from the genesis block.) Your node is correctly rejecting it, and should still be syncing from other nodes.

**Comment by sskyspear** [comment]
thx a lot for your reply. sync was very slow (5mbit internet, 4g ram), seems its very dependent on theese 2.  Is there a way to move or specify blockchain location on hard drive?

**Comment by Pajace** [comment]
Does any one can share blockchain.bin with me, I am not sure why my aeon daemon's Blockchain Height always 999, and receive the following message :


`2017-Dec-14 01:09:12.610334 [RPC1]ERROR /home/pajacemobile/aeon-0.9.14.0/src/cryptonote_core/checkpoints.cpp:71 CHECKPOINT FAILED FOR HEIGHT 1000. EXPECTED HASH: <bc6458452fd0575a314089bf302f6fd68ebaa2d689c42f3365293b96bbdf1f25>, FETCHED HASH: <7da255de9d1698ff2d51c657a03dbd5e5870adc83fbc9b5fc5b865772f44c284>
2017-Dec-14 01:09:12.610391 [RPC1]ERROR /home/pajacemobile/aeon-0.9.14.0/src/cryptonote_core/blockchain_storage.cpp:1607 CHECKPOINT VALIDATION FAILED
2017-Dec-14 01:09:12.610402 [RPC1]ERROR /home/pajacemobile/aeon-0.9.14.0/src/cryptonote_core/cryptonote_core.cpp:423 mined block failed verification
2017-Dec-14 01:09:14.736807 [RPC0]ERROR /home/pajacemobile/aeon-0.9.14.0/src/cryptonote_core/checkpoints.cpp:71 CHECKPOINT FAILED FOR HEIGHT 1000. EXPECTED HASH: <bc6458452fd0575a314089bf302f6fd68ebaa2d689c42f3365293b96bbdf1f25>, FETCHED HASH: <e90679fbf9572f845b8f538d96ea68a4b05eeee4f68f4e8ad73f2d09d0c3ab02>
2017-Dec-14 01:09:14.736857 [RPC0]ERROR /home/pajacemobile/aeon-0.9.14.0/src/cryptonote_core/blockchain_storage.cpp:1607 CHECKPOINT VALIDATION FAILED
2017-Dec-14 01:09:14.736872 [RPC0]ERROR /home/pajacemobile/aeon-0.9.14.0/src/cryptonote_core/cryptonote_core.cpp:423 mined block failed verification`

And my pool's network is very strange , always 2.01 H/sec

**Comment by stoomart** [comment]
@sskyspear 4Gb won't due for aeond because it keeps the entire blocks in memory, the slowness is due to your swap space getting crushed. Either upgrade RAM (16Gb worked for me) or sync your wallet with a public daemon.
