### ISSUE TITLE
How do we get the wallet address for AEON?

### ISSUE THREAD

**Issue by BitcoinsNinja** [aeonix/aeon-legacy#52]
Iam a beginner to this. Kindly excuse.
When I use the command "start_mining", I need to specify the wallet address. Iam trying to mine AEON.
How do I get my AEON wallet address?

Appreciate the response.

Vikas

**Comment by sammy007** [comment]
`simplewallet --generate-new-wallet myaeon`

It's a question for `#aeon` AT freenode channel or for [bitcointalk thread](https://bitcointalk.org/index.php?topic=641696.new#new), not for issue tracker.

**Comment by BitcoinsNinja** [comment]
Thanks a lot for the quick revert. My wallet address is now generated.

The AEOND.exe is synchronizing. Should take a few hours I suppose.

The command "set_log 4" speeds up the sync?

**Comment by BitcoinsNinja** [comment]
Thanks a lot for the quick revert.

**Comment by BitcoinsNinja** [comment]
[wallet WmssmW]: start_mining 1
Error: mining has NOT been started: daemon is busy. Please try later

SO, the AEOND.exe should finish the sync before I start mining?

**Comment by iamsmooth** [comment]
No set_log 4 will produce very verbose logging and either slow down syncing or have little effect on speed.

**Comment by iamsmooth** [comment]
Please close issue as there isn't actually an issue here that needs addressing, just questions (as above, please try IRC, reddit, bitcointalk, etc.)

**Comment by BitcoinsNinja** [comment]
Thanks mate.  I appreciate it.

On Wed, 5 Apr 2017 at 2:24 AM, iamsmooth <notifications@github.com> wrote:

No set_log 4 will produce very verbose logging and either slow down syncing
or have little effect.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aeonix/aeon/issues/52#issuecomment-291628823>, or mute
the thread
