### ISSUE TITLE
Password reset or recovery?

### ISSUE THREAD

**Issue by imrecsoka** [aeonix/aeon-legacy#59]
Hi,  dont understand looking at the help of simplewallet.exe --help
how on earth you recover the password to the wallet
I have just created it and done some mining, but it looks like my password was maybe not typed nicely when i created one...

I have the passphrase words.... but how the hell do i recover the wallet. It is not user friendly.

**Comment by lenhartjames** [comment]
This is what I run on my Mac so that it requests the seed:

./simplewallet --restore-deterministic-wallet

**Comment by iamsmooth** [comment]
this is the correct answer ^

also note that you must type all the words on one line

If this solves your problem please close the issue
