### ISSUE TITLE
diff command will display wrong hash rate after hard fork

### ISSUE THREAD

**Issue by iamsmooth** [aeonix/aeon-legacy#6]
block target of 60 is hard coded in daemon_commands_handler.h

**Comment by notsuhz** [comment]
Sophia is fine with me. +1

**Comment by bpacholek** [comment]
for sure not Cronos because you are very late

**Comment by velvet-valdes** [comment]
Athena +1 for giving Zeus the mother of all headaches.

http://www.desy.de/gna/interpedia/greek_myth/athenaBirth.html

**Comment by d0uglas72** [comment]
Sophia  +1
