### ISSUE TITLE
compilation on ubuntu 17.04 need a new "-Wno-error" option

### ISSUE THREAD

**Issue by Arux-BTT** [aeonix/aeon-legacy#61]
on ubuntu 17.04, using make does not produce binaries
compilation failed because of a -Werror=unused-but-set-variable warning treated as an error.

first, i guess it's due to a newer version of gcc (6.3) but compilation is ok with gcc 6.3 on former ubuntu 16.10.
so i don't have any explanation but  it appears that "-Wno-error=unused-but-set-variable" must be added to cmakelist.txt

**Comment by stoffu** [comment]
Addressed by PR #65

**Comment by stoffu** [comment]
@Arux-BTT  Could you please this issue unless it isn't solved?

**Comment by Arux-BTT** [comment]
Thanks you stoffu.
And sorry for delay, I did not follow closely these last months.
