### ISSUE TITLE
Error @ 45% During make

### ISSUE THREAD

**Issue by 4Reallive** [aeonix/aeon-legacy#64]
[makelog.txt](https://github.com/aeonix/aeon/files/1058103/makelog.txt)

Logs are attached

FROM ubuntu:16.04
RUN apt-get update && apt-get install -y cmake g++ libboost-all-dev
RUN mkdir /opt/git &&\
        cd /opt/git &&\
        git clone https://github.com/aeonix/aeon.git &&\
        cd aeon &&\
        make

**Comment by stoffu** [comment]
```
/opt/git/aeon/contrib/epee/include/serialization/keyvalue_serialization_overloads.h:129:46: error: variable ‘it’ set but not used [-Werror=unused-but-set-variable]
       typename stl_container::const_iterator it = container.begin();
                                              ^~
cc1plus: all warnings being treated as errors
```

Apparently a harmless warning is being treated as an error. Commenting out that line (by adding `//` to the beginning of the line) will allow the compilation to continue.

**Comment by stoffu** [comment]
Addressed by PR #65

**Comment by 4Reallive** [comment]
Thanks for the comment. Anyone reading this, a easier workaround is to use the 'make -k' parameter which continues and ignores warnings. Good Stuff, ill include it in my docker file.

**Comment by stoffu** [comment]
@4Reallive Could you please close this issue?

**Comment by 4Reallive** [comment]
sorry learning the ropes
