### ISSUE TITLE
Frequent reorgs seen on network

### ISSUE THREAD

**Issue by iamsmooth** [aeonix/aeon-legacy#68]
Under investigation

**Comment by ihuntrocks** [comment]
I noticed several identified attempts at double spends in my aeond log around the time of the reorganizations. Related?

**Comment by divra056** [comment]
I noticed several blocks mined by my pool become orphaned.
Blocks: 836801, 836802, 836860 with Block Hash: 8f4af4ffd84f28db05e927626f79faa25de6433343f2d93b2a7431d68d80d6de 	e32e3166ea17e22d3c53d272797d04c247f203b46de5ce249786a6e59a8ece65 3210b16708f4cdf3b06383c2b64adfdcfed7e01c04009a8dfbcd7461a971a503 become orphaned after maturity was more 60 and pool unblock reward payments for this blocks. 

I temporary enlarge Maturity Depth Requirement on pool to prevent payments for orphaned block to miners.

**Comment by ihuntrocks** [comment]
Can we get a status update on this issue?

**Comment by iamsmooth** [comment]
Can anyone report on whether this has continued to happen since June 20 or is still happening?

**Comment by iamsmooth** [comment]
I've reviewed both logs on my own nodes as well as public pool block logs and I do not see any frequent or excessive reorgs for some time (months)

My best understanding at this point is that improved operational procedures at pools such as provisioning adequate hardware, using the --disable-save option, redundant nodes, taking care to use the correct version with fixes, etc. have resolved the incidents of these drop-out-of-sync conditions that led to mining on a fork and resulting reorgs.

I will continue to monitor the network and accept reports but I do not see a current problem in practice, nor has anyone else reported one, so I'm closing the issue. Will reopen if the problem recurs.

**Comment by iamsmooth** [comment]
Also in #85 I provided some deployment recommendations in the README file similar to those mentioned above

**Comment by iamsmooth** [comment]
Also in #83 I provided some deployment recommendations in the README file similar to those mentioned above
