### ISSUE TITLE
boost 1.65 compiling issue

### ISSUE THREAD

**Issue by frankcoderL** [aeonix/aeon-legacy#79]
Doesn't compile anymore on Arch Linux with boost 1.65 (it dit compile with boost 1.64 two months ago).
How can this be fixed?
Thanks!

****
$ make
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  

CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:106 (find_package)
CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:106 (find_package)
...
****

BOOST 1.64 a two months ago, everything Ok

$ make
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- The C compiler identification is GNU 7.1.1
-- The CXX compiler identification is GNU 7.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   chrono
--   regex
--   serialization
--   program_options
--   atomic
-- Found Git: /usr/bin/git
****

**Comment by ronnylov** [comment]
I am having the same issue on Arch Linux.

**Comment by frankcoderL** [comment]
It might also be related with cmake?
Aeon did compile with cmake 3.8.2-1 and boost 1.64, and it doesn't compile with cmake 3.9.3-1 and boost 1.65

I had to recompile Monero as well after upgrade to boost 1.65  , Monero does compile but it gives also Cmake Warnings (i can't remember anymore there where cmake warnings before or not on Monero).

I'm not sure if the next compile messages of Monero helps or not, but after several  cmake warnings that seems to be more or less identical on aeon, Monero  does find boost 1.65 and compiles 100%

`CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):`
` Imported targets not available for Boost version 106501`
`Call Stack (most recent call first):`
 ` /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)`
 ` /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:643 (find_package)`
... several other cmake warnings ...
`-- Found Boost Version: 106501`

**Comment by anthonytam** [comment]
I just completed a build on Arch linux with boost 1.65 and cmake 3.9.2 with the same warnings, however there are no issues with the build

```
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/lib/hardening-wrapper/bin/cc
-- Check for working C compiler: /usr/lib/hardening-wrapper/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/hardening-wrapper/bin/c++
-- Check for working CXX compiler: /usr/lib/hardening-wrapper/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:106 (find_package)


CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:106 (find_package)


CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:106 (find_package)


CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:106 (find_package)


CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:106 (find_package)


CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:106 (find_package)


CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:106 (find_package)


CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:106 (find_package)


-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   chrono
--   regex
--   serialization
--   program_options
-- Found Git: /usr/bin/git
-- Found PythonInterp: /usr/bin/python (found version "3.6.2") 
-- Configuring done
-- Generating done

```

**Comment by ghost** [comment]
> I just completed a build on Arch linux with boost 1.65 and cmake 3.9.2 with the same warnings, however there are no issues with the build

+1
Build is working as described on Arch with boost-1.65.1-1.

**Comment by frankcoderL** [comment]
Indeed, it builds on Arch Linux again, and without warnings.
Was it a Arch Linux issue not a aeon issue?

```
$ make
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   chrono
--   regex
--   serialization
--   program_options
--   atomic
-- Found Git: /usr/bin/git
-- Found PythonInterp: /usr/bin/python (found version "3.6.2") 
-- Configuring done
-- Generating done
```

**Comment by frankcoderL** [comment]
it works again :-)
