### ISSUE TITLE
simplewallet dies when aeond is saving blockchain

### ISSUE THREAD

**Issue by kuligokm** [aeonix/aeon-legacy#80]
I am running a pool and every 12 hours aeond is saving the blockchain to disk, this takes about 2 minutes.  During this time simplewallet is running in rpc mode to accept commands from the pool software but I get the following errors:

2017-Sep-26 18:54:49.664504 [RPC0]ERROR /home/minerkmk/Downloads/aeon-0.9.12.0/src/wallet/wallet2.cpp:278 res.status == CORE_RPC_STATUS_BUSY. THROW EXCEPTION: error::daemon_busy
2017-Sep-26 18:54:49.664879 [RPC0]/home/minerkmk/Downloads/aeon-0.9.12.0/src/wallet/wallet2.cpp:278:N5tools5error11daemon_busyE: daemon is busy, request = getblocks.bin
2017-Sep-26 18:54:49.664961 [RPC0]Another try pull_blocks (try_count=0)...
2017-Sep-26 18:54:49.751728 [RPC0]ERROR /home/minerkmk/Downloads/aeon-0.9.12.0/src/wallet/wallet2.cpp:278 res.status == CORE_RPC_STATUS_BUSY. THROW EXCEPTION: error::daemon_busy
2017-Sep-26 18:54:49.751792 [RPC0]/home/minerkmk/Downloads/aeon-0.9.12.0/src/wallet/wallet2.cpp:278:N5tools5error11daemon_busyE: daemon is busy, request = getblocks.bin
2017-Sep-26 18:54:49.751845 [RPC0]Another try pull_blocks (try_count=1)...
2017-Sep-26 18:54:49.839783 [RPC0]ERROR /home/minerkmk/Downloads/aeon-0.9.12.0/src/wallet/wallet2.cpp:278 res.status == CORE_RPC_STATUS_BUSY. THROW EXCEPTION: error::daemon_busy
2017-Sep-26 18:54:49.839857 [RPC0]/home/minerkmk/Downloads/aeon-0.9.12.0/src/wallet/wallet2.cpp:278:N5tools5error11daemon_busyE: daemon is busy, request = getblocks.bin
2017-Sep-26 18:54:49.839915 [RPC0]Another try pull_blocks (try_count=2)...
2017-Sep-26 18:54:49.927745 [RPC0]ERROR /home/minerkmk/Downloads/aeon-0.9.12.0/src/wallet/wallet2.cpp:278 res.status == CORE_RPC_STATUS_BUSY. THROW EXCEPTION: error::daemon_busy
2017-Sep-26 18:54:49.927819 [RPC0]/home/minerkmk/Downloads/aeon-0.9.12.0/src/wallet/wallet2.cpp:278:N5tools5error11daemon_busyE: daemon is busy, request = getblocks.bin
2017-Sep-26 18:54:49.927869 [RPC0]ERROR /home/minerkmk/Downloads/aeon-0.9.12.0/src/wallet/wallet2.cpp:353 pull_blocks failed, try_count=3
2017-Sep-26 18:54:49.928480 [RPC0]ERROR /home/minerkmk/Downloads/aeon-0.9.12.0/contrib/epee/include/net/abstract_tcp_server2.inl:502 Exception at server worker thread, what=daemon is busy

I believe one solution would be to implement a wait function if the daemon is busy to give it  time to write the blockchain to disk.

**Comment by stoffu** [comment]
IIRC, a daemon flag `--disable-save` was added relatively recently to address this issue.

**Comment by kuligokm** [comment]
When aeond restarts will it need to resync the block chain?   I'd prefer to pick up where I left off, or close to it, if the process dies

**Comment by stoffu** [comment]
No, having to resync the blockchain on every restart would be horrible. aeond saves the blockchain when it exits normally with the `exit` command. You can also manually trigger the blockchain saving with the `save` command.

**Comment by kuligokm** [comment]
Wouldn't it be cleaner for the wallet to pause if aeond is busy and check back potentially more than 3 times? If you look at the timestamps the retries happen within milliseconds of each other. I haven't looked further but once wallet2.cpp throws the exception after 3 tries it never attempts again

**Comment by aeonix** [comment]
More retries seems okay

**Comment by kuligokm** [comment]
from the  log entry it looks like the while loop burns through 3 retries in ~3/10ths of a second while the blockchain save is running for ~2min 30sec writing to an SSD.  It seems the retry count would  have to be significantly higher and the while loop is just going to eat CPU cycles in this instance.  Would it make sense to look for the CORE_BUSY message being thrown as an exception from pull_blocks and treat it differently than the other exceptions?  If aeond is reporting that it's busy we know it's up so I don't know if we necessarily need to increment the try_count in that case, sleeping and trying again might suffice.  If it's one of the other exceptions I think it should only try 3 times because it indicates an acutal error being reported from aeond

**Comment by iamsmooth** [comment]
You're right, more tries isn't enough to fix the problem.

What happens after those errors?

**Comment by kuligokm** [comment]
simplewallet still services rpc requests but it never re-executes the refresh() method so the balance of the wallet is reported as "stale" via the get_balance method until I kill simplewallet and restart it.  At that point it re-syncs with the blockchain and reflects the accurate balance of the wallet.

2017-Sep-29 07:03:41.410374 [RPC0]HTTP [127.0.0.1] POST /json_rpc
2017-Sep-29 07:03:41.436227 [RPC0]/json_rpc[getbalance] processed with 1/0/0ms
2017-Sep-29 07:04:41.401473 [RPC0]HTTP [127.0.0.1] POST /json_rpc
2017-Sep-29 07:04:41.402668 [RPC0]/json_rpc[getbalance] processed with 1/0/0ms
2017-Sep-29 07:05:41.396598 [RPC0]HTTP [127.0.0.1] POST /json_rpc
2017-Sep-29 07:05:41.396697 [RPC0]/json_rpc[getbalance] processed with 0/0/0ms
2017-Sep-29 07:06:41.398064 [RPC0]HTTP [127.0.0.1] POST /json_rpc
2017-Sep-29 07:06:41.398158 [RPC0]/json_rpc[getbalance] processed with 0/0/0ms
2017-Sep-29 07:07:41.400544 [RPC0]HTTP [127.0.0.1] POST /json_rpc
2017-Sep-29 07:07:41.400637 [RPC0]/json_rpc[getbalance] processed with 1/0/0ms
2017-Sep-29 07:08:41.404138 [RPC0]HTTP [127.0.0.1] POST /json_rpc
2017-Sep-29 07:08:41.404225 [RPC0]/json_rpc[getbalance] processed with 0/0/0ms

**Comment by iamsmooth** [comment]
Try the fix I just pushed to master 

#81

**Comment by kuligokm** [comment]
just cloned and compiled.  Started up aeond and simplewallet then executed a manual save of the blockchain in aeond.  Simplewallet responded as expected.  The process tried 3 times and failed, waited for a period of time and then executed the refresh method again.  Once aeond finished saving the blockchain, simplewallet resumed normal operation of pulling new blocks off the blockchain to update wallet balance.

Thanks for the quick turn-around, closing issue.
