### ISSUE TITLE
Error: daemon is busy. Please try later

### ISSUE THREAD

**Issue by kmanev073** [aeonix/aeon-legacy#95]
Hello!

Everytime I try to transfer some AEONs to HitBTC I get this error. "Error: daemon is busy. Please try later"

I run this command "transfer 0 addr 50" and I have enough AEONs. I run Windows x64 and Phoenix (0.9.13.0). I have the aeond running and fully sync, then I start the simplewallet but I cant make the transaction.

Any idea how can I fix this? Thank you in advance!

**Comment by stoffu** [comment]
Does the result change if you use one of these public nodes?
https://www.reddit.com/r/Aeon/comments/73829j/public_nodes_new_list/

**Comment by kmanev073** [comment]
Thank you, it worked!

**Comment by stoffu** [comment]
Nice! Please close this issue.
