### ISSUE TITLE
Can't save blockchain or exit daemon

### ISSUE THREAD

**Issue by pslobo** [aeonix/aeon-legacy#96]
This is probably related to issue #91 but on more than one Mac I've left the daemon running overnight or during the day. When I finally try and save the blockchain or exit the daemon, my Mac essentially grinds to a holt while attempting to dump to the file. I have yet to manage a successful sync due to this.

Running version `aeon v0.9.13.0` installed view homebrew.

Edit: 

For reference, it's now 11:42 and still not finished...

```sh
exit                                                               
2017-Oct-04 08:51:05.601928 [node] Stop signal sent                
2017-Oct-04 10:40:39.672691 [P2P3]Blockchain stored OK.            
2017-Oct-04 10:40:40.513945 [SRV_MAIN]net_service loop stopped.    
2017-Oct-04 10:40:40.514018 [SRV_MAIN]p2p net loop stopped         
2017-Oct-04 10:40:40.514035 [SRV_MAIN]Stopping core rpc server...  
2017-Oct-04 10:40:40.583988 [SRV_MAIN]Deinitializing core...       
2017-Oct-04 10:40:40.584079 [SRV_MAIN]Mining has been stopped, 0 finished                                                             
2017-Oct-04 10:40:40.619211 [SRV_MAIN]Storing blockchain...  
```

**Comment by jtgrassie** [comment]
Observing the same thing here on mac.

**Comment by jtgrassie** [comment]
It did eventually save for me but took a long time with no feedback.
